require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '15.1'
prepare_react_native_project!
install! 'cocoapods', :deterministic_uuids => false

target 'UCPunjabi' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()
  #pod 'FirebaseCore', :modular_headers => true
  #pod 'GoogleUtilities', :modular_headers => true
  #$RNFirebaseAsStaticFramework = true;

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'ReactNativeAudioToolkit', :path => '../node_modules/@react-native-community/audio-toolkit'
  target 'UCPunjabiTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      # Set `mac_catalyst_enabled` to `true` in order to apply patches
      # necessary for Mac Catalyst builds
      :mac_catalyst_enabled => false
    )
  end
end