export const numbersData = {
  '੦ - ੯':
    [
      { id: 1, numberGurmukhi: '੦', punjabi: 'ਸਿਫ਼ਰ', numberArabic: '0', audioId: 'n00', uri: require('../../assets/number-gifs/na00.gif')},
      { id: 2, numberGurmukhi: '੧', punjabi: 'ਇਕ', numberArabic: '1', audioId: 'n01', uri: require('../../assets/number-gifs/na01.gif')},
      { id: 3, numberGurmukhi: '੨', punjabi: 'ਦੋ', numberArabic: '2', audioId: 'n02', uri: require('../../assets/number-gifs/na02.gif')},
      { id: 4, numberGurmukhi: '੩', punjabi: 'ਤਿੰਨ', numberArabic: '3', audioId: 'n03', uri: require('../../assets/number-gifs/na03.gif')},
      { id: 5, numberGurmukhi: '੪', punjabi: 'ਚਾਰ', numberArabic: '4', audioId: 'n04', uri: require('../../assets/number-gifs/na04.gif')},
      { id: 6, numberGurmukhi: '੫', punjabi: 'ਪੰਜ', numberArabic: '5', audioId: 'n05', uri: require('../../assets/number-gifs/na05.gif')},
      { id: 7, numberGurmukhi: '੬', punjabi: 'ਛੇ', numberArabic: '6', audioId: 'n06', uri: require('../../assets/number-gifs/na06.gif')},
      { id: 8, numberGurmukhi: '੭', punjabi: 'ਸੱਤ', numberArabic: '7', audioId: 'n07', uri: require('../../assets/number-gifs/na07.gif')},
      { id: 9, numberGurmukhi: '੮', punjabi: 'ਅੱਠ', numberArabic: '8', audioId: 'n08', uri: require('../../assets/number-gifs/na08.gif')},
      { id: 10, numberGurmukhi: '੯', punjabi: 'ਨੌਂ', numberArabic: '9', audioId: 'n09', uri: require('../../assets/number-gifs/na09.gif')},
    ],
  '੧੦ - ੧੯':
    [
      { id: 11, numberGurmukhi: '੧੦', punjabi: 'ਦਸ', numberArabic: '10', audioId: 'n10' },
      { id: 12, numberGurmukhi: '੧੧', punjabi: 'ਗਿਆਰਾਂ', numberArabic: '11', audioId: 'n11' },
      { id: 13, numberGurmukhi: '੧੨', punjabi: 'ਬਾਰਾਂ', numberArabic: '12', audioId: 'n12' },
      { id: 14, numberGurmukhi: '੧੩', punjabi: 'ਤੇਰਾਂ', numberArabic: '13', audioId: 'n13' },
      { id: 15, numberGurmukhi: '੧੪', punjabi: 'ਚੌਦਾਂ', numberArabic: '14', audioId: 'n14' },
      { id: 16, numberGurmukhi: '੧੫', punjabi: 'ਪੰਦਰਾਂ', numberArabic: '15', audioId: 'n15' },
      { id: 17, numberGurmukhi: '੧੬', punjabi: 'ਸੋਲਾਂ', numberArabic: '16', audioId: 'n16' },
      { id: 18, numberGurmukhi: '੧੭', punjabi: 'ਸਤਾਰਾਂ', numberArabic: '17', audioId: 'n17' },
      { id: 19, numberGurmukhi: '੧੮', punjabi: 'ਅਠਾਰਾਂ', numberArabic: '18', audioId: 'n18' },
      { id: 20, numberGurmukhi: '੧੯', punjabi: 'ਉੱਨੀ', numberArabic: '19', audioId: 'n19' },
    ],
  '੨੦ - ੨੯':
    [
      { id: 21, numberGurmukhi: '੨੦', punjabi: 'ਵੀਹ', numberArabic: '20', audioId: 'n20' },
      { id: 22, numberGurmukhi: '੨੧', punjabi: 'ਇਕੀ', numberArabic: '21', audioId: 'n21' },
      { id: 23, numberGurmukhi: '੨੨', punjabi: 'ਬਾਈ', numberArabic: '22', audioId: 'n22' },
      { id: 24, numberGurmukhi: '੨੩', punjabi: 'ਤੇਈ', numberArabic: '23', audioId: 'n23' },
      { id: 25, numberGurmukhi: '੨੪', punjabi: 'ਚੌਵੀ', numberArabic: '24', audioId: 'n24' },
      { id: 26, numberGurmukhi: '੨੫', punjabi: 'ਪੱਚੀ', numberArabic: '25', audioId: 'n25' },
      { id: 27, numberGurmukhi: '੨੬', punjabi: 'ਛੱਬੀ', numberArabic: '26', audioId: 'n26' },
      { id: 28, numberGurmukhi: '੨੭', punjabi: 'ਸਤਾਈ', numberArabic: '27', audioId: 'n27' },
      { id: 29, numberGurmukhi: '੨੮', punjabi: 'ਅਠਾਈ', numberArabic: '28', audioId: 'n28' },
      { id: 30, numberGurmukhi: '੨੯', punjabi: 'ਅਠਾਈ', numberArabic: '29', audioId: 'n29' },
    ],
  '੩੦ - ੩੯':
    [
      { id: 31, numberGurmukhi: '੩੦', punjabi: 'ਤੀਹ', numberArabic: '30', audioId: 'n30' },
      { id: 32, numberGurmukhi: '੩੧', punjabi: 'ਇਕੱਤੀ', numberArabic: '31', audioId: 'n31' },
      { id: 33, numberGurmukhi: '੩੨', punjabi: 'ਬੱਤੀ', numberArabic: '32', audioId: 'n32' },
      { id: 34, numberGurmukhi: '੩੩', punjabi: 'ਤੇਤੀ', numberArabic: '33', audioId: 'n33' },
      { id: 35, numberGurmukhi: '੩੪', punjabi: 'ਚੌਂਤੀ', numberArabic: '34', audioId: 'n34' },
      { id: 36, numberGurmukhi: '੩੫', punjabi: 'ਪੈਂਤੀ', numberArabic: '35', audioId: 'n35' },
      { id: 37, numberGurmukhi: '੩੬', punjabi: 'ਛੱਤੀ', numberArabic: '36', audioId: 'n36' },
      { id: 38, numberGurmukhi: '੩੭', punjabi: 'ਸੈਂਤੀ', numberArabic: '37', audioId: 'n37' },
      { id: 39, numberGurmukhi: '੩੮', punjabi: 'ਅਠੱਤੀ', numberArabic: '38', audioId: 'n38' },
      { id: 40, numberGurmukhi: '੩੯', punjabi: 'ਉਣਤਾਲੀ', numberArabic: '39', audioId: 'n39' },
    ],
  '੪੦ - ੪੯':
    [
      { id: 41, numberGurmukhi: '੪੦', punjabi: 'ਚਾਲੀ', numberArabic: '40', audioId: 'n40' },
      { id: 42, numberGurmukhi: '੪੧', punjabi: 'ਇਕਤਾਲੀ', numberArabic: '41', audioId: 'n41' },
      { id: 43, numberGurmukhi: '੪੨', punjabi: 'ਬਿਆਲੀ', numberArabic: '42', audioId: 'n42' },
      { id: 44, numberGurmukhi: '੪੩', punjabi: 'ਤਰਤਾਲੀ', numberArabic: '43', audioId: 'n43' },
      { id: 45, numberGurmukhi: '੪੪', punjabi: 'ਚੁਤਾਲੀ', numberArabic: '44', audioId: 'n44' },
      { id: 46, numberGurmukhi: '੪੫', punjabi: 'ਪੰਤਾਲੀ', numberArabic: '45', audioId: 'n45' },
      { id: 47, numberGurmukhi: '੪੬', punjabi: 'ਛਿਆਲੀ', numberArabic: '46', audioId: 'n46' },
      { id: 48, numberGurmukhi: '੪੭', punjabi: 'ਸੰਤਾਲੀ', numberArabic: '47', audioId: 'n47' },
      { id: 49, numberGurmukhi: '੪੮', punjabi: 'ਅਠਤਾਲੀ', numberArabic: '48', audioId: 'n48' },
      { id: 50, numberGurmukhi: '੪੯', punjabi: 'ਉਣੰਜਾ', numberArabic: '49', audioId: 'n49' },
    ],
  '੫੦ - ੫੯':
    [
      { id: 51, numberGurmukhi: '੫੦', punjabi: 'ਪੰਜਾਹ', numberArabic: '50', audioId: 'n50' },
      { id: 52, numberGurmukhi: '੫੧', punjabi: 'ਇਕਵੰਜਾ', numberArabic: '51', audioId: 'n51' },
      { id: 53, numberGurmukhi: '੫੨', punjabi: 'ਬਵੰਜਾ', numberArabic: '52', audioId: 'n52' },
      { id: 54, numberGurmukhi: '੫੩', punjabi: 'ਤਰਵੰਜਾ', numberArabic: '53', audioId: 'n53' },
      { id: 55, numberGurmukhi: '੫੪', punjabi: 'ਚੁਰੰਜਾ', numberArabic: '54', audioId: 'n54' },
      { id: 56, numberGurmukhi: '੫੫', punjabi: 'ਪਚਵੰਜਾ', numberArabic: '55', audioId: 'n55' },
      { id: 57, numberGurmukhi: '੫੬', punjabi: 'ਛਪੰਜਾ', numberArabic: '56', audioId: 'n56' },
      { id: 58, numberGurmukhi: '੫੭', punjabi: 'ਸਤਵੰਜਾ', numberArabic: '57', audioId: 'n57' },
      { id: 59, numberGurmukhi: '੫੮', punjabi: 'ਅਠਵੰਜਾ', numberArabic: '58', audioId: 'n58' },
      { id: 60, numberGurmukhi: '੫੯', punjabi: 'ਉਣਾਹਠ', numberArabic: '59', audioId: 'n59' },
    ],
  '੬੦ - ੬੯':
    [
      { id: 61, numberGurmukhi: '੬੦', punjabi: 'ਸੱਠ', numberArabic: '60', audioId: 'n60' },
      { id: 62, numberGurmukhi: '੬੧', punjabi: 'ਇਕਾਹਠ', numberArabic: '61', audioId: 'n61' },
      { id: 63, numberGurmukhi: '੬੨', punjabi: 'ਬਾਹਠ', numberArabic: '62', audioId: 'n62' },
      { id: 64, numberGurmukhi: '੬੩', punjabi: 'ਤਰੇਹਠ', numberArabic: '63', audioId: 'n63' },
      { id: 65, numberGurmukhi: '੬੪', punjabi: 'ਚੌਂਹਠ', numberArabic: '64', audioId: 'n64' },
      { id: 66, numberGurmukhi: '੬੫', punjabi: 'ਪੈਂਹਠ', numberArabic: '65', audioId: 'n65' },
      { id: 67, numberGurmukhi: '੬੬', punjabi: 'ਛਿਆਹਠ', numberArabic: '66', audioId: 'n66' },
      { id: 68, numberGurmukhi: '੬੭', punjabi: 'ਸਤਾਹਠ', numberArabic: '67', audioId: 'n67' },
      { id: 69, numberGurmukhi: '੬੮', punjabi: 'ਅਠਾਹਠ', numberArabic: '68', audioId: 'n68' },
      { id: 70, numberGurmukhi: '੬੯', punjabi: 'ਉਣੱਤਰ', numberArabic: '69', audioId: 'n69' },
    ],
  '੭੦ - ੭੯':
    [
      { id: 71, numberGurmukhi: '੭੦', punjabi: 'ਸੱਤਰ', numberArabic: '70', audioId: 'n70' },
      { id: 72, numberGurmukhi: '੭੧', punjabi: 'ਇਕ੍ਹੱਤਰ', numberArabic: '71', audioId: 'n71' },
      { id: 73, numberGurmukhi: '੭੨', punjabi: 'ਬਹੱਤਰ', numberArabic: '72', audioId: 'n72' },
      { id: 74, numberGurmukhi: '੭੩', punjabi: 'ਤਿਹੱਤਰ', numberArabic: '73', audioId: 'n73' },
      { id: 75, numberGurmukhi: '੭੪', punjabi: 'ਚੁਹੱਤਰ', numberArabic: '74', audioId: 'n74' },
      { id: 76, numberGurmukhi: '੭੫', punjabi: 'ਪੰਝੱਤਰ', numberArabic: '75', audioId: 'n75' },
      { id: 77, numberGurmukhi: '੭੬', punjabi: 'ਛਿਹੱਤਰ', numberArabic: '76', audioId: 'n76' },
      { id: 78, numberGurmukhi: '੭੭', punjabi: 'ਸਤੱਤਰ', numberArabic: '77', audioId: 'n77' },
      { id: 79, numberGurmukhi: '੭੮', punjabi: 'ਅਠੱਤਰ', numberArabic: '78', audioId: 'n78' },
      { id: 80, numberGurmukhi: '੭੯', punjabi: 'ਉਣਾਸੀ', numberArabic: '79', audioId: 'n79' },
    ],
  '੮੦ - ੮੯':
    [
      { id: 81, numberGurmukhi: '੮੦', punjabi: 'ਅੱਸੀ', numberArabic: '80', audioId: 'n80' },
      { id: 82, numberGurmukhi: '੮੧', punjabi: 'ਇਕਾਸੀ', numberArabic: '81', audioId: 'n81' },
      { id: 83, numberGurmukhi: '੮੨', punjabi: 'ਬਿਆਸੀ', numberArabic: '82', audioId: 'n82' },
      { id: 84, numberGurmukhi: '੮੩', punjabi: 'ਤਰਾਸੀ', numberArabic: '83', audioId: 'n83' },
      { id: 85, numberGurmukhi: '੮੪', punjabi: 'ਚੁਰਾਸੀ', numberArabic: '84', audioId: 'n84' },
      { id: 86, numberGurmukhi: '੮੫', punjabi: 'ਪਚਾਸੀ', numberArabic: '85', audioId: 'n85' },
      { id: 87, numberGurmukhi: '੮੬', punjabi: 'ਛਿਆਸੀ', numberArabic: '86', audioId: 'n86' },
      { id: 88, numberGurmukhi: '੮੭', punjabi: 'ਸਤਾਸੀ', numberArabic: '87', audioId: 'n87' },
      { id: 89, numberGurmukhi: '੮੮', punjabi: 'ਅਠਾਸੀ', numberArabic: '88', audioId: 'n88' },
      { id: 90, numberGurmukhi: '੮੯', punjabi: 'ਉਣਾਨਵੇਂ', numberArabic: '89', audioId: 'n89' },
    ],
  '੯੦ - ੯੯':
    [
      { id: 91, numberGurmukhi: '੯੦', punjabi: 'ਨੱਬੇ', numberArabic: '90', audioId: 'n90' },
      { id: 92, numberGurmukhi: '੯੧', punjabi: 'ਇਕਾਨਵੇਂ', numberArabic: '91', audioId: 'n91' },
      { id: 93, numberGurmukhi: '੯੨', punjabi: 'ਬਾਨਵੇਂ', numberArabic: '92', audioId: 'n92' },
      { id: 94, numberGurmukhi: '੯੩', punjabi: 'ਤਰਾਨਵੇਂ', numberArabic: '93', audioId: 'n93' },
      { id: 95, numberGurmukhi: '੯੪', punjabi: 'ਚੁਰਾਨਵੇਂ', numberArabic: '94', audioId: 'n94' },
      { id: 96, numberGurmukhi: '੯੫', punjabi: 'ਪਚਾਨਵੇਂ', numberArabic: '95', audioId: 'n95' },
      { id: 97, numberGurmukhi: '੯੬', punjabi: 'ਛਿਆਨਵੇਂ', numberArabic: '96', audioId: 'n96' },
      { id: 98, numberGurmukhi: '੯੭', punjabi: 'ਸਤਾਨਵੇਂ', numberArabic: '97', audioId: 'n97' },
      { id: 99, numberGurmukhi: '੯੮', punjabi: 'ਅਠਾਨਵੇਂ', numberArabic: '98', audioId: 'n98' },
      { id: 100, numberGurmukhi: '੯੯', punjabi: 'ਨੜ੍ਹਿੰਨਵੇਂ', numberArabic: '99', audioId: 'n99' },
    ],
  '>= ੧੦੦':
    [
      { id: 101, numberGurmukhi: '੧੦੦', punjabi: 'ਇਕ ਸੌ', numberArabic: '100', audioId: 'n100_1_sau' },
      { id: 102, numberGurmukhi: '੧੦੦੦', punjabi: 'ਇਕ ਹਜ਼ਾਰ', numberArabic: '1000', audioId: 'n1000_1_hazaar' },
      { id: 103, numberGurmukhi: '੧੦,੦੦੦', punjabi: 'ਦਸ ਹਜ਼ਾਰ', numberArabic: '10,000', audioId: 'n10000_10_hazaar' },
      { id: 104, numberGurmukhi: '੧੦੦,੦੦੦', punjabi: 'ਇਕ ਲੱਖ', numberArabic: '100,000', audioId: 'n100000_1_lakh' },
      { id: 105, numberGurmukhi: '੧,੦੦੦,੦੦੦', punjabi: 'ਦਸ ਲੱਖ', numberArabic: '1,000,000', audioId: 'n1000000_10_lakh' },
      { id: 106, numberGurmukhi: '੧੦,੦੦੦,੦੦੦', punjabi: 'ਇਕ ਕਰੋੜ', numberArabic: '10,000,000', audioId: 'n10000000_1_crore'},
      { id: 107, numberGurmukhi: '੧੦੦,੦੦੦,੦੦੦', punjabi: 'ਦਸ ਕਰੋੜ', numberArabic: '100,000,000', audioId: 'n100000000_10_crore'},
      { id: 108, numberGurmukhi: '੧,੦੦੦,੦੦੦,੦੦੦', punjabi: 'ਇਕ ਅਰਬ', numberArabic: '1,000,000,000', audioId: 'n1000000000_1_urb'},
    ],
}