export const vocabularyData = {
    "Family": //mod2
    {
        Adjectives:
            [
                { id:1, gender: '', punjabi:'ਖੁਸ਼', starred: false, english:'happy', audioId:'voc0201'},
                { id:2, gender: '', punjabi:'ਦੋਵੇਂ', starred: false, english:'both', audioId:'voc0202'},
                { id:3, gender: '', punjabi:'ਇਕੱਠੇ', starred: false, english:'together', audioId:'voc0203'},
                { id:4, gender: '', punjabi:'ਵੱਡਾ', starred: false, english:'big or older', audioId:'voc0204'},
                { id:5, gender: '', punjabi:'ਛੋਟਾ', starred: false, english:'small or younger', audioId:'voc0205'},
            ],
        Nouns:
            [
                { id:1, gender: 'm', punjabi:'ਘਰ', starred: false, english:'home', audioId:'voc0206'},
                { id:2, gender: 'f', punjabi:'ਗੱਲਬਾਤ', starred: false, english:'conversation', audioId:'voc0207'},
                { id:3, gender: 'm', punjabi:'ਪਿਆਰ', starred: false, english:'love', audioId:'voc0208'},
                { id:4, gender: 'm', punjabi:'ਕੰਮ', starred: false, english:'work', audioId:'voc0209'},
                { id:5, gender: 'f', punjabi:'ਮਦਦ', starred: false, english:'help', audioId:'voc0210'},
                { id:6, gender: 'm', punjabi:'ਬਜ਼ੁਰਗ', starred: false, english:'elder', audioId:'voc0211'},
                { id:7, gender: 'm', punjabi:'ਡਾਕਟਰ', starred: false, english:'physician', audioId:'voc0212'},
                { id:8, gender: 'm', punjabi:'ਅਧਿਆਪਕ', starred: false, english:'teacher', audioId:'voc0213'},
                { id:9, gender: 'm', punjabi:'ਸਕੂਲ', starred: false, english:'school', audioId:'voc0214'},
                { id:10, gender: 'f', punjabi:'ਸੈਰ', starred: false, english:'stroll', audioId:'voc0215'},
                { id:11, gender: 'm', punjabi:'ਰਿਸ਼ਤੇਦਾਰ', starred: false, english:'relatives', audioId:'voc0216'},
                { id:12, gender: 'm', punjabi:'ਪਰਿਵਾਰ', starred: false, english:'family', audioId:'voc0217'},
                { id:13, gender: 'm', punjabi:'ਜੀਅ', starred: false, english:'family members', audioId:'voc0218'},
                { id:14, gender: 'f', punjabi:'ਮਾਤਾ/ਮਾਂ', starred: false, english:'mother', audioId:'voc0219'},
                { id:15, gender: 'm', punjabi:'ਪਿਤਾ', starred: false, english:'father', audioId:'voc0220'},
                { id:16, gender: 'm', punjabi:'ਭਰਾ', starred: false, english:'brother', audioId:'voc0221'},
                { id:17, gender: 'f', punjabi:'ਭੈਣ', starred: false, english:'sister', audioId:'voc0222'},
                { id:18, gender: 'f', punjabi:'ਧੀ', starred: false, english:'daughter', audioId:'voc0223'},
                { id:19, gender: 'm', punjabi:'ਪੁੱਤਰ', starred: false, english:'son', audioId:'voc0224'},
                { id:20, gender: 'm', punjabi:'ਪਤੀ', starred: false, english:'husband', audioId:'voc0225'},
                { id:21, gender: 'f', punjabi:'ਪਤਨੀ', starred: false, english:'wife', audioId:'voc0226'},
                { id:22, gender: 'f', punjabi:'ਨਾਨੀ', starred: false, english:'maternal grandmother', audioId:'voc0227'},
                { id:23, gender: 'm', punjabi:'ਨਾਨਾ', starred: false, english:'maternal grandfather', audioId:'voc0228'},
                { id:24, gender: 'f', punjabi:'ਮਾਸੀ', starred: false, english:'mother`s sister', audioId:'voc0229'},
                { id:25, gender: 'm', punjabi:'ਮਾਮਾ', starred: false, english:'mother`s brother', audioId:'voc0230'},
                { id:26, gender: 'f', punjabi:'ਮਾਮੀ', starred: false, english:'mama`s wife', audioId:'voc0231'},
                { id:27, gender: 'f', punjabi:'ਦਾਦੀ', starred: false, english:'paternal grandmother', audioId:'voc0232'},
                { id:28, gender: 'm', punjabi:'ਦਾਦਾ', starred: false, english:'paternal grandfather', audioId:'voc0233'},
                { id:29, gender: 'm', punjabi:'ਚਾਚਾ', starred: false, english:'father`s younger brother', audioId:'voc0234'},
                { id:30, gender: 'f', punjabi:'ਚਾਚੀ', starred: false, english:'chacha`s wife', audioId:'voc0235'},
            ],
        Verbs:
            [
                { id:1, gender: '', punjabi:'ਹੋਣਾ', starred: false, english:'to be', audioId:'voc0236'},
                { id:2, gender: '', punjabi:'ਕਰਨਾ', starred: false, english:'to do', audioId:'voc0237'},
                { id:3, gender: '', punjabi:'ਖੇਡਣਾ', starred: false, english:'to play', audioId:'voc0238'},
                { id:4, gender: '', punjabi:'ਪੜ੍ਹਨਾ', starred: false, english:'to study or read', audioId:'voc0239'},
            ],
        Others:
            [
                { id:1, gender: '', punjabi:'ਵੀ', starred: false, english:'too/also', audioId:'voc0240'},
                { id:2, gender: '', punjabi:'ਅਤੇ', starred: false, english:'and', audioId:'voc0241'},
                { id:3, gender: '', punjabi:'ਵਿਚ', starred: false, english:'in', audioId:'voc0242'},
                { id:4, gender: '', punjabi:'ਅਸੀਂ', starred: false, english:'we', audioId:'voc0243'},
                { id:5, gender: '', punjabi:'ਕਿਵੇਂ', starred: false, english:'how', audioId:'voc0244'},
                { id:6, gender: '', punjabi:'ਕਦੋਂ', starred: false, english:'when', audioId:'voc0245'},
                { id:7, gender: '', punjabi:'ਕੌਣ', starred: false, english:'who', audioId:'voc0246'},
                { id:8, gender: '', punjabi:'ਕਿਉਂ', starred: false, english:'why', audioId:'voc0247'},
                { id:9, gender: '', punjabi:'ਕਿੱਥੇ', starred: false, english:'where', audioId:'voc0248'},
                { id:10, gender: '', punjabi:'ਕੀ', starred: false, english:'what', audioId:'voc0249'},
            ],
    },
    "Home": //mod3
    {
        Nouns:
            [
                { id:1, gender: 'm', punjabi:'ਐਤਵਾਰ', starred: false, english:'Sunday', audioId:'voc0301'},
                { id:2, gender: 'm', punjabi:'ਸੋਮਵਾਰ', starred: false, english:'Monday', audioId:'voc0302'},
                { id:3, gender: 'm', punjabi:'ਮੰਗਲਵਾਰ', starred: false, english:'Tuesday', audioId:'voc0303'},
                { id:4, gender: 'm', punjabi:'ਬੁੱਧਵਾਰ', starred: false, english:'Wednesday', audioId:'voc0304'},
                { id:5, gender: 'm', punjabi:'ਵੀਰਵਾਰ', starred: false, english:'Thursday', audioId:'voc0305'},
                { id:6, gender: 'm', punjabi:'ਸ਼ੁੱਕਰਵਾਰ', starred: false, english:'Friday', audioId:'voc0306'},
                { id:7, gender: 'm', punjabi:'ਸ਼ਨਿੱਚਰਵਾਰ', starred: false, english:'Saturday', audioId:'voc0307'},
                { id:8, gender: '', punjabi:'ਅਪਾਰਟਮੈਂਟ', starred: false, english:'apartment', audioId:'voc0308'},
                { id:9, gender: 'm', punjabi:'ਕਮਰਾ', starred: false, english:'room', audioId:'voc0309'},
                { id:10, gender: 'f', punjabi:'ਥਾਂ', starred: false, english:'space, place', audioId:'voc0310'},
                { id:11, gender: 'f', punjabi:'ਬੈਠਕ', starred: false, english:'sitting room', audioId:'voc0311'},
                { id:12, gender: 'f', punjabi:'ਰਸੋਈ', starred: false, english:'kitchen', audioId:'voc0312'},
                { id:13, gender: 'm', punjabi:'ਬੈੱਡਰੂਮ', starred: false, english:'bedroom', audioId:'voc0313'},
                { id:14, gender: 'm', punjabi:'ਗ਼ੁਸਲਖ਼ਾਨਾ', starred: false, english:'bathroom', audioId:'voc0314'},
                { id:15, gender: 'm', punjabi:'ਵਿਹੜਾ', starred: false, english:'yard', audioId:'voc0315'},
                { id:16, gender: 'f', punjabi:'ਸੜਕ', starred: false, english:'road, street', audioId:'voc0316'},
                { id:17, gender: 'f', punjabi:'ਛੱਤ', starred: false, english:'roof, ceiling', audioId:'voc0317'},
                { id:18, gender: 'm', punjabi:'ਦਰਵਾਜਾ', starred: false, english:'door', audioId:'voc0318'},
                { id:19, gender: 'f', punjabi:'ਖਿੜਕੀ', starred: false, english:'window', audioId:'voc0319'},
                { id:20, gender: 'f', punjabi:'ਚਾਹ', starred: false, english:'tea', audioId:'voc0320'},
                { id:21, gender: '', punjabi:'ਫਰਨੀਚਰ', starred: false, english:'furniture', audioId:'voc0321'},
                { id:22, gender: '', punjabi:'ਬੁਰਸ਼', starred: false, english:'brush', audioId:'voc0322'},
                { id:23, gender: 'm', punjabi:'ਕੱਪੜੇ', starred: false, english:'clothes', audioId:'voc0323'},
                { id:24, gender: 'm', punjabi:'ਨਾਸ਼ਤਾ', starred: false, english:'breakfast', audioId:'voc0324'},
                { id:25, gender: 'f', punjabi:'ਸਫ਼ਾਈ', starred: false, english:'cleanliness', audioId:'voc0325'},
                { id:26, gender: 'm', punjabi:'ਅਰਾਮ', starred: false, english:'rest', audioId:'voc0326'},
                { id:27, gender: 'f', punjabi:'ਰਾਤ', starred: false, english:'night', audioId:'voc0327'},
                { id:28, gender: 'f', punjabi:'ਸਵੇਰ', starred: false, english:'morning', audioId:'voc0328'},
                { id:29, gender: 'f', punjabi:'ਸ਼ਾਮ', starred: false, english:'evening', audioId:'voc0329'},
                { id:30, gender: 'f', punjabi:'ਦੁਪਹਿਰ', starred: false, english:'at noon', audioId:'voc0330'},
                { id:31, gender: '', punjabi:'ਵਜੇ', starred: false, english:'o`clock', audioId:'voc0332'},
            ],
        Verbs:
            [
                { id:1, gender: '', punjabi:'ਜਾਗਣਾ', starred: false, english:'to wake up', audioId:'voc0333'},
                { id:2, gender: '', punjabi:'ਬੈਠਣਾ', starred: false, english:'to sit', audioId:'voc0334'},
                { id:3, gender: '', punjabi:'ਦੇਖਣਾ', starred: false, english:'to see', audioId:'voc0335'},
                { id:4, gender: '', punjabi:'ਖਾਣਾ', starred: false, english:'to eat', audioId:'voc0336'},
                { id:5, gender: '', punjabi:'ਜਾਣਾ', starred: false, english:'to go', audioId:'voc0337'},
                { id:6, gender: '', punjabi:'ਧੋਣਾ', starred: false, english:'to wash', audioId:'voc0338'},
                { id:7, gender: '', punjabi:'ਸੌਣਾ', starred: false, english:'to sleep', audioId:'voc0339'},
                { id:8, gender: '', punjabi:'ਆਉਣਾ', starred: false, english:'to come', audioId:'voc0340'},
                { id:9, gender: '', punjabi:'ਨਹਾਉਣਾ', starred: false, english:'to take a shower', audioId:'voc0341'},
                { id:10, gender: '', punjabi:'ਬਣਾਉਣਾ', starred: false, english:'to make', audioId:'voc0342'},
                { id:11, gender: '', punjabi:'ਚਲਾਉਣਾ', starred: false, english:'to start or drive', audioId:'voc0343'},
                { id:12, gender: '', punjabi:'ਰਹਿਣਾ', starred: false, english:'to live', audioId:'voc0344'},
            ],
        Others:
            [
                { id:1, gender: '', punjabi:'ਅੰਦਰ', starred: false, english:'inside', audioId:'voc0345'},
                { id:2, gender: '', punjabi:'ਬਾਹਰ', starred: false, english:'outside', audioId:'voc0346'},
                { id:3, gender: '', punjabi:'ਹਰ ਰੋਜ਼', starred: false, english:'every day', audioId:'voc0347'},
                { id:4, gender: '', punjabi:'ਵੇਲੇ', starred: false, english:'at the time', audioId:'voc0348'},
                { id:5, gender: '', punjabi:'ਨੇੜੇ', starred: false, english:'near/close by', audioId:'voc0349'},
                { id:6, gender: '', punjabi:'ਪਿੱਛੇ', starred: false, english:'back/behind', audioId:'voc0350'},
                { id:7, gender: '', punjabi:'ਫਿਰ', starred: false, english:'then', audioId:'voc0351'},
                { id:8, gender: '', punjabi:'ਲਈ', starred: false, english:'for', audioId:'voc0352'},
                { id:9, gender: '', punjabi:'ਪਰ', starred: false, english:'but', audioId:'voc0353'},
                { id:10, gender: '', punjabi:'ਤੇ/ਉੱਤੇ', starred: false, english:'at/on', audioId:'voc0354'},
                { id:11, gender: '', punjabi:'ਥੱਲੇ', starred: false, english:'downstairs', audioId:'voc0355'},
                { id:12, gender: '', punjabi:'ਸਾਡਾ', starred: false, english:'ours', audioId:'voc0356'},
                { id:13, gender: '', punjabi:'ਕਈ', starred: false, english:'many', audioId:'voc0357'},
            ],
    },
    "Body & Health": //mod4
    {
        Adjectives:
            [
                { id:1, gender: '', punjabi:'ਤੰਦਰੁਸਤ', starred: false, english:'healthy', audioId:'voc0430'},
                { id:2, gender: '', punjabi:'ਉਦਾਸ', starred: false, english:'sad', audioId:'voc0431'},
                { id:3, gender: '', punjabi:'ਬਿਮਾਰ', starred: false, english:'sick', audioId:'voc0432'},
                { id:4, gender: '', punjabi:'ਢਿੱਲਾ', starred: false, english:'unwell', audioId:'voc0433'},
                { id:5, gender: '', punjabi:'ਕਮਜ਼ੋਰ', starred: false, english:'weak', audioId:'voc0434'},
            ],
        Nouns:
            [
                { id:1, gender: 'm', punjabi:'ਗੁੱਸਾ', starred: false, english:'anger', audioId:'voc0401'},
                { id:2, gender: 'f', punjabi:'ਘਬਰਾਹਟ', starred: false, english:'anxiety', audioId:'voc0402'},
                { id:3, gender: 'f', punjabi:'ਬੇਚੈਨੀ', starred: false, english:'restlessness', audioId:'voc0403'},
                { id:4, gender: '', punjabi:'ਸਟਰੈੱਸ', starred: false, english:'stress', audioId:'voc0404'},
                { id:5, gender: '', punjabi:'ਟੈਨਸ਼ਨ', starred: false, english:'tension', audioId:'voc0405'},
                { id:6, gender: 'm', punjabi:'ਫ਼ਿਕਰ', starred: false, english:'worry', audioId:'voc0406'},
                { id:7, gender: 'm', punjabi:'ਜ਼ੁਕਾਮ', starred: false, english:'bad cold', audioId:'voc0407'},
                { id:8, gender: 'f', punjabi:'ਠੰਢ', starred: false, english:'cold', audioId:'voc0408'},
                { id:9, gender: 'f', punjabi:'ਖੰਘ', starred: false, english:'cough', audioId:'voc0409'},
                { id:10, gender: 'm', punjabi:'ਥਕਾਵਟ', starred: false, english:'fatigue', audioId:'voc0410'},
                { id:11, gender: 'm', punjabi:'ਬੁਖਾਰ', starred: false, english:'fever', audioId:'voc0411'},
                { id:12, gender: 'f', punjabi:'ਛਿੱਕ', starred: false, english:'sneeze', audioId:'voc0412'},
                { id:13, gender: 'f', punjabi:'ਜਾਂਚ', starred: false, english:'diagnosis', audioId:'voc0413'},
                { id:14, gender: 'f', punjabi:'ਸਿਰ ਦਰਦ', starred: false, english:'headache', audioId:'voc0414'},
                { id:15, gender: 'f', punjabi:'ਸਿਹਤ', starred: false, english:'health', audioId:'voc0415'},
                { id:16, gender: 'm', punjabi:'ਦਿਲ', starred: false, english:'heart', audioId:'voc0416'},
                { id:17, gender: 'f', punjabi:'ਗਰਮੀ', starred: false, english:'heat, summer', audioId:'voc0417'},
                { id:18, gender: 'f', punjabi:'ਭੁੱਖ', starred: false, english:'hunger', audioId:'voc0418'},
                { id:19, gender: 'f', punjabi:'ਦਵਾਈ', starred: false, english:'medicine', audioId:'voc0419'},
                { id:20, gender: 'm', punjabi:'ਮਨ', starred: false, english:'mind', audioId:'vvoc0420'},
                { id:21, gender: 'f', punjabi:'ਗੋਲੀ', starred: false, english:'pill', audioId:'voc0421'},
                { id:22, gender: 'f', punjabi:'ਤ੍ਰੇਹ', starred: false, english:'thirst', audioId:'voc0422'},
                { id:23, gender: 'f', punjabi:'ਨੀਂਦ', starred: false, english:'sleep', audioId:'voc0423'},
                { id:24, gender: 'm', punjabi:'ਖਿਆਲ', starred: false, english:'thought', audioId:'voc0424'},
                { id:25, gender: 'm', punjabi:'ਗਲਾ', starred: false, english:'throat', audioId:'voc0425'},
                { id:26, gender: 'm', punjabi:'ਇਲਾਜ', starred: false, english:'treatment', audioId:'voc0426'},
                { id:27, gender: 'f', punjabi:'ਅੱਖਾਂ', starred: false, english:'eyes', audioId:'voc0427'},
                { id:28, gender: 'm', punjabi:'ਜੀਵਨ', starred: false, english:'life', audioId:'voc0428'},
                { id:29, gender: 'f', punjabi:'ਮਾਸਪੇਸ਼ੀਆਂ', starred: false, english:'muscle', audioId:'voc0429'},
            ],
        Verbs:
            [
                { id:1, gender: '', punjabi:'ਰੋਣਾ', starred: false, english:'to cry', audioId:'voc0435'},
                { id:2, gender: '', punjabi:'ਪੀਣਾ', starred: false, english:'to drink', audioId:'voc0436'},
                { id:3, gender: '', punjabi:'ਦਿਲ ਕਰਨਾ', starred: false, english:'to feel like', audioId:'voc0437'},
                { id:4, gender: '', punjabi:'ਲੱਗਣਾ', starred: false, english:'to feel, appear or seem', audioId:'voc0438'},
                { id:5, gender: '', punjabi:'ਦੁਖਣਾ', starred: false, english:'To hurt', audioId:'voc0439'},
                { id:6, gender: '', punjabi:'ਹੋਣਾ', starred: false, english:'to occur', audioId:'voc0440'},
                { id:7, gender: '', punjabi:'ਲੈਣਾ', starred: false, english:'to take', audioId:'voc0441'},
            ],
        Others:
            [
                { id:1, gender: '', punjabi:'ਕੋਈ ਨਾ', starred: false, english:'never mind', audioId:'voc0442'},
                { id:2, gender: '', punjabi:'ਨੂੰ', starred: false, english:'to', audioId:'voc0443'},
                { id:3, gender: '', punjabi:'ਤੁਹਾਨੂੰ', starred: false, english:'to you', audioId:'voc0444'},
                { id:4, gender: '', punjabi:'ਥੋੜ੍ਹਾ', starred: false, english:'a little bit', audioId:'voc0445'},
                { id:5, gender: '', punjabi:'ਕੋਈ', starred: false, english:'any/some', audioId:'voc0446'},
                { id:6, gender: '', punjabi:'ਕਿਉਂਕਿ', starred: false, english:'because', audioId:'voc0447'},
                { id:7, gender: '', punjabi:'ਕੁਝ ਵੀ ਨਹੀਂ', starred: false, english:'nothing', audioId:'voc0448'},
                { id:8, gender: '', punjabi:'ਕੁਝ', starred: false, english:'something/anything/some', audioId:'voc0449'},
                { id:9, gender: '', punjabi:'ਜਦੋਂ/ਤਦੋਂ/ਤੋਂ/ਉਦੋਂ', starred: false, english:'when/then', audioId:'voc0450'},
            ],
    },
    "Market & Food": //mod5
    {
        Adjectives:
            [
                { id:1, gender: '', punjabi:'ਚੌਥਾ ਹਿੱਸਾ', starred: false, english:'one fourth', audioId:'voc0531'},
                { id:2, gender: '', punjabi:'ਤੀਜਾ ਹਿੱਸਾ', starred: false, english:'one third', audioId:'voc0532'},
                { id:3, gender: '', punjabi:'ਪੂਰਾ', starred: false, english:'full/all', audioId:'voc0533'},
                { id:4, gender: '', punjabi:'ਅੱਧਾ', starred: false, english:'half', audioId:'voc0534'},
                { id:5, gender: '', punjabi:'ਘੱਟ', starred: false, english:'less', audioId:'voc0535'},
                { id:6, gender: '', punjabi:'ਵੱਧ', starred: false, english:'more than', audioId:'voc0536'},
                { id:7, gender: '', punjabi:'ਤਾਜ਼ਾ', starred: false, english:'fresh', audioId:'voc0537'},
                { id:8, gender: '', punjabi:'ਮਸਾਲੇਦਾਰ', starred: false, english:'spicy', audioId:'voc0538'},
                { id:9, gender: '', punjabi:'ਤੰਦੂਰੀ', starred: false, english:'tandoori (cooked in a clay oven)', audioId:'voc0539'},
                { id:10, gender: '', punjabi:'ਸੁਆਦ', starred: false, english:'delicious', audioId:'voc0540'},
                { id:11, gender: '', punjabi:'ਸਸਤਾ', starred: false, english:'cheap/inexpensive', audioId:'voc0541'},
                { id:12, gender: '', punjabi:'ਮਹਿੰਗਾ', starred: false, english:'expensive', audioId:'voc0542'},

            ],
        Nouns:
            [
                { id:1, gender: 'm', punjabi:'ਮੱਖਣ', starred: false, english:'butter', audioId:'voc0501'},
                { id:2, gender: 'f', punjabi:'ਮੈਂਗੋ ਲੱਸੀ', starred: false, english:'mango buttermilk', audioId:'voc0502'},
                { id:3, gender: 'm', punjabi:'ਘਿਓ', starred: false, english:'clarified butter', audioId:'voc0503'},
                { id:4, gender: 'm', punjabi:'ਪਕੌੜਾ', starred: false, english:'fritters', audioId:'voc0504'},
                { id:5, gender: 'm', punjabi:'ਫਲ', starred: false, english:'fruit', audioId:'voc0505'},
                { id:6, gender: 'm', punjabi:'ਪਨੀਰ', starred: false, english:'cheese', audioId:'voc0506'},
                { id:7, gender: 'm', punjabi:'ਪਰੌਂਠਾ', starred: false, english:'pan fried flat bread', audioId:'voc0507'},
                { id:8, gender: 'f', punjabi:'ਮੱਕੀ ਦੀ ਰੋਟੀ', starred: false, english:'corn tortilla', audioId:'voc0508'},
                { id:9, gender: 'f', punjabi:'ਰੋਟੀ', starred: false, english:'flour tortilla', audioId:'voc0509'},
                { id:10, gender: 'm', punjabi:'ਦਹੀਂ', starred: false, english:'yogurt', audioId:'voc0510'},
                { id:11, gender: 'f', punjabi:'ਦਾਲ', starred: false, english:'lentil (dish)', audioId:'voc0511'},
                { id:12, gender: 'm', punjabi:'ਚੌਲ', starred: false, english:'rice', audioId:'voc0512'},
                { id:13, gender: 'm', punjabi:'ਪਿਆਜ', starred: false, english:'onion', audioId:'voc0513'},
                { id:14, gender: 'm', punjabi:'ਮਟਰ', starred: false, english:'pea', audioId:'voc0514'},
                { id:15, gender: 'm', punjabi:'ਆਲੂ', starred: false, english:'potato', audioId:'voc0515'},
                { id:16, gender: 'm', punjabi:'ਸਾਗ', starred: false, english:'a dish made with spinach and \nmustard greens', audioId:'voc0516'},
                { id:17, gender: 'm', punjabi:'ਟਮਾਟਰ', starred: false, english:'tomato', audioId:'voc0517'},
                { id:18, gender: 'f', punjabi:'ਸਬਜ਼ੀ', starred: false, english:'vegetable', audioId:'voc0518'},
                { id:19, gender: 'm', punjabi:'ਹਰਾ ਧਨੀਆ', starred: false, english:'cilantro', audioId:'voc0519'},
                { id:20, gender: 'm', punjabi:'ਲਸਣ', starred: false, english:'garlic', audioId:'voc0520'},
                { id:21, gender: 'm', punjabi:'ਅਦਰਕ', starred: false, english:'ginger', audioId:'voc0521'},
                { id:22, gender: 'f', punjabi:'ਲਾਲ ਮਿਰਚ', starred: false, english:'red chili', audioId:'voc0522'},
                { id:23, gender: 'm', punjabi:'ਲੂਣ', starred: false, english:'salt', audioId:'voc0523'},
                { id:24, gender: 'm', punjabi:'ਗਰਮ ਮਸਾਲਾ', starred: false, english:'spice mix', audioId:'voc0524'},
                { id:25, gender: 'f', punjabi:'ਹਲਦੀ', starred: false, english:'turmeric', audioId:'voc0525'},
                { id:26, gender: 'm', punjabi:'ਰੰਗ', starred: false, english:'color', audioId:'voc0526'},
                { id:27, gender: 'f', punjabi:'ਦੁਕਾਨ', starred: false, english:'store', audioId:'voc0527'},
                { id:28, gender: 'm', punjabi:'ਦੁਕਾਨਦਾਰ', starred: false, english:'storekeeper', audioId:'voc0528'},
                { id:29, gender: 'm', punjabi:'ਗਾਹਕ', starred: false, english:'customer', audioId:'voc0529'},
                { id:30, gender: 'm', punjabi:'ਤੜਕਾ', starred: false, english:'tadka (tempered spices in \nheated oil)', audioId:'voc0530'},
            ],
        Verbs:
            [
                { id:1, gender: '', punjabi:'ਚਾਹੁਣਾ', starred: false, english:'to need/to want', audioId:'voc0543'},
                { id:2, gender: '', punjabi:'ਪਾਉਣਾ', starred: false, english:'to add', audioId:'voc0544'},
                { id:3, gender: '', punjabi:'ਪੁੱਛਣਾ', starred: false, english:'to ask', audioId:'voc0545'},
                { id:4, gender: '', punjabi:'ਲਿਆਉਣਾ', starred: false, english:'to bring', audioId:'voc0546'},
                { id:5, gender: '', punjabi:'ਖਰੀਦਣਾ', starred: false, english:'to buy', audioId:'voc0547'},
                { id:6, gender: '', punjabi:'ਕੱਟਣਾ', starred: false, english:'to cut', audioId:'voc0548'},
                { id:7, gender: '', punjabi:'ਤਲਨਾ', starred: false, english:'to deep fry', audioId:'voc0549'},
                { id:8, gender: '', punjabi:'ਦੇਣਾ', starred: false, english:'to give', audioId:'voc0550'},
                { id:9, gender: '', punjabi:'ਪਕਾਉਣਾ', starred: false, english:'to cook', audioId:'voc0551'},
                { id:10, gender: '', punjabi:'ਖਰਚਣਾ', starred: false, english:'to spend', audioId:'voc0552'},
                { id:11, gender: '', punjabi:'ਭੁੰਨਣਾ', starred: false, english:'to roast', audioId:'voc0553'},
                { id:12, gender: '', punjabi:'ਪਸੰਦ ਹੋਣਾ', starred: false, english:'to be liked', audioId:'voc0554'},

            ],
        Others:
            [
                { id:1, gender: '', punjabi:'ਸਿਰਫ਼', starred: false, english:'only', audioId:'voc0555'},
                { id:2, gender: '', punjabi:'ਕਦੀ-ਕਦੀ', starred: false, english:'sometimes', audioId:'voc0556'},
                { id:3, gender: '', punjabi:'ਆਮ ਕਰਕੇ', starred: false, english:'usually', audioId:'voc0557'},
                { id:4, gender: '', punjabi:'ਕਿਰਪਾ ਕਰਕੇ', starred: false, english:'please', audioId:'voc0558'},
                { id:5, gender: '', punjabi:'ਦੇਣਾ', starred: false, english:'belonging to', audioId:'voc0559'},
                { id:6, gender: '', punjabi:'ਕੋਲ', starred: false, english:'with/near', audioId:'voc0560'},
                { id:7, gender: '', punjabi:'ਕਿੰਨਾ', starred: false, english:'how much', audioId:'voc0561'},
                { id:8, gender: '', punjabi:'ਬੱਸ', starred: false, english:'that`s enough', audioId:'voc0562'},
            ],
    },
    "Faith & Celebrations": //mod6
    {
        Adjectives:
            [
                { id:1, gender: '', punjabi:'ਇਕ ਦੂਸਰੇ ਨੂੰ', starred: false, english:'each other', audioId:'voc0653'},
                { id:2, gender: '', punjabi:'ਮਸ਼ਹੂਰ', starred: false, english:'famous', audioId:'voc0654'},
                { id:3, gender: '', punjabi:'ਨਵਾਂ', starred: false, english:'new', audioId:'voc0655'},
                { id:4, gender: '', punjabi:'ਸਭ ਤੋਂ ਵਧੀਆ', starred: false, english:'the best', audioId:'voc0656'},
                { id:5, gender: '', punjabi:'ਹਜ਼ਾਰਾਂ', starred: false, english:'thousands', audioId:'voc0657'},
                { id:6, gender: '', punjabi:'ਬੁਰਾ', starred: false, english:'bad/evil', audioId:'voc0658'},
                          
            ],
        Nouns:
            [
                { id:1, gender: 'f', punjabi:'ਮੇਲਾ', starred: false, english:'fair', audioId:'voc0601'},
                { id:2, gender: 'f', punjabi:'ਰੌਣਕ', starred: false, english:'festive crowd', audioId:'voc0602'},
                { id:3, gender: 'f', punjabi:'ਭੀੜ', starred: false, english:'crowd', audioId:'voc0603'},
                { id:4, gender: 'm', punjabi:'ਖਾਣ-ਪੀਣ', starred: false, english:'eat/drink', audioId:'voc0604'},
                { id:5, gender: 'f', punjabi:'ਮਸਤੀ', starred: false, english:'enjoyment', audioId:'voc0605'},
                { id:6, gender: 'm', punjabi:'ਤਿਉਹਾਰ', starred: false, english:'festival', audioId:'voc0606'},
                { id:7, gender: 'f', punjabi:'ਆਤਿਸ਼ਬਾਜ਼ੀ', starred: false, english:'fireworks display', audioId:'voc0607'},
                { id:8, gender: 'm', punjabi:'ਪਟਾਕੇ', starred: false, english:'fireworks', audioId:'voc0608'},
                { id:9, gender: 'm', punjabi:'ਤੋਹਫ਼ਾ', starred: false, english:'gift', audioId:'voc0609'},
                { id:10, gender: 'm', punjabi:'ਲੋਕ', starred: false, english:'people', audioId:'voc0610'},
                { id:11, gender: 'm', punjabi:'ਧੂਮਧਾਮ', starred: false, english:'enthusiasm', audioId:'voc0611'},
                { id:12, gender: 'm', punjabi:'ਧਰਮ', starred: false, english:'religion', audioId:'voc0612'},
                { id:13, gender: 'f', punjabi:'ਸੰਗਤ', starred: false, english:'congregation', audioId:'voc0613'},
                { id:14, gender: 'm', punjabi:'ਗੁਰਦੁਆਰਾ', starred: false, english:'Sikh place of worship', audioId:'voc0614'},
                { id:15, gender: 'm', punjabi:'ਹੋਲਾ ਮਹੱਲਾ', starred: false, english:'Sikh spring festival', audioId:'voc0615'},
                { id:16, gender: 'f', punjabi:'ਵਿਸਾਖੀ', starred: false, english:'Punjabi harvest festival', audioId:'voc0616'},
                { id:17, gender: 'm', punjabi:'ਕੀਰਤਨ', starred: false, english:'devotional singing', audioId:'voc0617'},
                { id:18, gender: 'm', punjabi:'ਲੰਗਰ', starred: false, english:'community meal', audioId:'voc0618'},
                { id:19, gender: 'f', punjabi:'ਪੂਜਾ', starred: false, english:'Hindu prayer', audioId:'voc0619'},
                { id:20, gender: 'f', punjabi:'ਅਰਦਾਸ', starred: false, english:'Sikh prayer', audioId:'voc0620'},
                { id:21, gender: 'f', punjabi:'ਦੁਆ', starred: false, english:'Muslim prayer', audioId:'voc0621'},
                { id:22, gender: 'm', punjabi:'ਮੰਦਰ', starred: false, english:'temple', audioId:'voc0622'},
                { id:23, gender: 'f', punjabi:'ਮਸਜਿਦ', starred: false, english:'mosque', audioId:'voc0623'},
                { id:24, gender: 'm', punjabi:'ਰਮਜ਼ਾਨ', starred: false, english:'Muslim holy month', audioId:'voc0624'},
                { id:25, gender: 'm', punjabi:'ਰੋਜ਼ਾ', starred: false, english:'Muslim fasting during Ramzan', audioId:'voc0625'},
                { id:26, gender: 'm', punjabi:'ਬੱਚਾ', starred: false, english:'child', audioId:'voc0626'},
                { id:27, gender: 'f', punjabi:'ਔਰਤ', starred: false, english:'woman', audioId:'voc0627'},
                { id:28, gender: 'm', punjabi:'ਆਦਮੀ', starred: false, english:'man', audioId:'voc0628'},
                { id:29, gender: 'f', punjabi:'ਮੋਮਬੱਤੀ', starred: false, english:'candle', audioId:'voc0629'},
                { id:30, gender: 'm', punjabi:'ਦੀਵਾ', starred: false, english:'clay lamp', audioId:'voc0630'},
                { id:31, gender: 'f', punjabi:'ਚੜ੍ਹਦੀ ਕਲਾ', starred: false, english:'eternal optimism', audioId:'voc0631'},
                { id:32, gender: 'm', punjabi:'ਮਹੀਨਾ', starred: false, english:'month', audioId:'voc0632'},
                { id:33, gender: 'm', punjabi:'ਮੌਸਮ', starred: false, english:'weather', audioId:'voc0633'},
                { id:34, gender: 'f', punjabi:'ਰੋਸ਼ਨੀ', starred: false, english:'light', audioId:'voc0634'},
                { id:35, gender: 'm', punjabi:'ਚੰਨ', starred: false, english:'moon', audioId:'voc0635'},
                { id:36, gender: 'f', punjabi:'ਜਿੱਤ', starred: false, english:'victory', audioId:'voc0636'},
                { id:37, gender: 'f', punjabi:'ਹਾਰ', starred: false, english:'defeat', audioId:'voc0637'},
                { id:38, gender: 'm', punjabi:'ਹਨੇਰਾ', starred: false, english:'darkness', audioId:'voc0638'},
                { id:39, gender: 'f', punjabi:'ਸਜਾਵਟ', starred: false, english:'decoration', audioId:'voc0639'},
                { id:40, gender: 'm', punjabi:'ਨਜ਼ਾਰਾ', starred: false, english:'view', audioId:'voc0640'},
                { id:41, gender: 'f', punjabi:'ਬੱਤੀ', starred: false, english:'lantern/wick/light', audioId:'voc0641'},
                { id:42, gender: 'f', punjabi:'ਲੜੀ', starred: false, english:'string', audioId:'voc0642'},
                { id:43, gender: 'm', punjabi:'ਬੂਹਾ', starred: false, english:'door', audioId:'voc0643'},
                { id:44, gender: 'f', punjabi:'ਬਾਰੀ', starred: false, english:'window', audioId:'voc0644'},
                { id:45, gender: 'm', punjabi:'ਗੁਰੂ ਗ੍ਰੰਥ ਸਾਹਿਬ', starred: false, english:'Sikh holy scripture', audioId:'voc0645'},
                { id:46, gender: 'm', punjabi:'ਵਾਹਿਗੁਰੂ', starred: false, english:'God (Sikh)', audioId:'voc0646'},
                { id:47, gender: 'm', punjabi:'ਭਗਵਾਨ', starred: false, english:'God (Hindu)', audioId:'voc0647'},
                { id:48, gender: 'm', punjabi:'ਅੱਲਾਹ', starred: false, english:'God (Muslim)', audioId:'voc0648'},
                { id:49, gender: 'm', punjabi:'ਰੱਬ', starred: false, english:'God (Universal)', audioId:'voc0649'},
                { id:50, gender: 'm', punjabi:'ਸਿੱਖ', starred: false, english:'Sikh', audioId:'voc0650'},
                { id:51, gender: 'm', punjabi:'ਹਿੰਦੂ', starred: false, english:'Hindu', audioId:'voc0651'},
                { id:52, gender: 'm', punjabi:'ਮੁਸਲਮਾਨ', starred: false, english:'Muslim', audioId:'voc0652'},
         
            ],
        Verbs:
            [
                { id:1, gender: '', punjabi:'ਮਨਾਉਣਾ', starred: false, english:'to celebrate', audioId:'voc0659'},
                { id:2, gender: '', punjabi:'ਸਜਾਉਣਾ', starred: false, english:'to decorate', audioId:'voc0660'},
                { id:3, gender: '', punjabi:'ਜਗਾਉਣਾ', starred: false, english:'to light up', audioId:'voc0661'},
                { id:4, gender: '', punjabi:'ਰੱਖਣਾ', starred: false, english:'to keep', audioId:'voc0662'},
                { id:5, gender: '', punjabi:'ਕਹਿਣਾ', starred: false, english:'to say', audioId:'voc0663'},
                { id:6, gender: '', punjabi:'ਤੋੜਨਾ', starred: false, english:'to break', audioId:'voc0664'},
                { id:7, gender: '', punjabi:'ਚੜ੍ਹਨਾ', starred: false, english:'to rise', audioId:'voc0665'},
                { id:8, gender: '', punjabi:'ਵਾਪਸ ਕਰਨਾ', starred: false, english:'to return', audioId:'voc0666'},
                { id:9, gender: '', punjabi:'ਜਗਮਗ ਕਰਨਾ', starred: false, english:'to sparkle', audioId:'voc0667'},
            ],
        Others:
            [
                { id:1, gender: '', punjabi:'ਵਧਾਈਆਂ', starred: false, english:'congratulations', audioId:'voc0668'},
                { id:2, gender: '', punjabi:'ਵਾਹਿਗੁਰੂ ਜੀ ਕਾ ਖਾਲਸਾ॥ \nਵਾਹਿਗੁਰੂ ਜੀ ਕੀ ਫ਼ਤਿਹ॥', starred: false, english:'Khalsa belongs to Waheguru. \nVictory belongs to Waheguru.', audioId:'voc0669'},
                { id:3, gender: '', punjabi:'ਇਸ ਤੋਂ ਇਲਾਵਾ', starred: false, english:'besides', audioId:'voc0670'},
                { id:4, gender: '', punjabi:'ਇਸ ਲਈ', starred: false, english:'for this reason/thus', audioId:'voc0671'},
            ],
    },
    "Clothes & Fashion": //mod7
    {
        Adjectives:
            [
                { id:1, gender: '', punjabi:'ਸਾਫ਼', starred: false, english:'clean', audioId:'voc0730'},
                { id:2, gender: '', punjabi:'ਸੂਤੀ', starred: false, english:'cotton', audioId:'voc0731'},
                { id:3, gender: '', punjabi:'ਗੂੜ੍ਹਾ', starred: false, english:'dark', audioId:'voc0732'},
                { id:4, gender: '', punjabi:'ਗੰਦਾ', starred: false, english:'dirty', audioId:'voc0733'},
                { id:5, gender: '', punjabi:'ਮੋਟਾ', starred: false, english:'fat', audioId:'voc0734'},
                { id:6, gender: '', punjabi:'ਪਤਲਾ', starred: false, english:'skinny/thin', audioId:'voc0735'},
                { id:7, gender: '', punjabi:'ਫਿੱਕਾ', starred: false, english:'light in color or quantity', audioId:'voc0736'},
                { id:8, gender: '', punjabi:'ਲੰਮਾ', starred: false, english:'long/tall', audioId:'voc0737'},
                { id:9, gender: '', punjabi:'ਖੁੱਲ੍ਹਾ', starred: false, english:'loose/open', audioId:'voc0738'},
                { id:10, gender: '', punjabi:'ਭੀੜਾ', starred: false, english:'tight', audioId:'voc0739'},
                { id:11, gender: '', punjabi:'ਢੁੱਕਵਾਂ', starred: false, english:'matching', audioId:'voc0740'},
                { id:12, gender: '', punjabi:'ਪੁਰਾਣਾ', starred: false, english:'old', audioId:'voc0741'},
                { id:13, gender: '', punjabi:'ਸਾਦਾ', starred: false, english:'simple', audioId:'voc0742'},
                { id:14, gender: '', punjabi:'ਸੋਹਣਾ', starred: false, english:'beautiful', audioId:'voc0743'},
                { id:15, gender: '', punjabi:'ਰੇਸ਼ਮੀ', starred: false, english:'silky', audioId:'voc0744'},
                { id:16, gender: '', punjabi:'ਇੱਕੋ-ਜਿਹੇ', starred: false, english:'similar', audioId:'voc0745'},
                { id:17, gender: '', punjabi:'ਵੱਖਰਾ', starred: false, english:'different', audioId:'voc0746'},
                { id:18, gender: '', punjabi:'ਲਾਲ', starred: false, english:'red', audioId:'voc0747'},
                { id:19, gender: '', punjabi:'ਸੰਤਰੀ', starred: false, english:'orange', audioId:'voc0748'},
                { id:20, gender: '', punjabi:'ਪੀਲਾ', starred: false, english:'yellow', audioId:'voc0749'},
                { id:21, gender: '', punjabi:'ਹਰਾ', starred: false, english:'green', audioId:'voc0750'},
                { id:22, gender: '', punjabi:'ਨੀਲਾ', starred: false, english:'blue', audioId:'voc0751'},
                { id:23, gender: '', punjabi:'ਗੁਲਾਬੀ', starred: false, english:'pink', audioId:'voc0752'},
                { id:24, gender: '', punjabi:'ਕਾਲਾ', starred: false, english:'black', audioId:'voc0753'},
                { id:25, gender: '', punjabi:'ਚਿੱਟਾ', starred: false, english:'white', audioId:'voc0754'},
                { id:26, gender: '', punjabi:'ਭੂਰਾ', starred: false, english:'brown', audioId:'voc0755'},
                { id:27, gender: '', punjabi:'ਸੁਨਹਿਰੀ', starred: false, english:'golden', audioId:'voc0756'},
                { id:28, gender: '', punjabi:'ਜਾਮਨੀ', starred: false, english:'purple', audioId:'voc0757'},
                { id:29, gender: '', punjabi:'ਫ਼ਿਰੋਜ਼ੀ', starred: false, english:'turquoise', audioId:'voc0758'},
                { id:30, gender: '', punjabi:'ਸਲੇਟੀ', starred: false, english:'gray', audioId:'voc0759'},
                { id:31, gender: '', punjabi:'ਬਦਾਮੀ', starred: false, english:'almond color', audioId:'voc0760'},
                { id:32, gender: '', punjabi:'ਮੋਰ-ਪੰਖੀਆ', starred: false, english:'peacock color', audioId:'voc0761'},
            
            ],
        Nouns:
            [
                { id:1, gender: 'f', punjabi:'ਬਾਂਹ', starred: false, english:'arm/sleeve', audioId:'voc0701'},
                { id:2, gender: 'f', punjabi:'ਚੁੰਨੀ', starred: false, english:'long scarf', audioId:'voc0702'},
                { id:3, gender: 'f', punjabi:'ਟੋਪੀ', starred: false, english:'hat', audioId:'voc0703'},
                { id:4, gender: 'm', punjabi:'ਹਿਜਾਬ', starred: false, english:'Muslim women`s head covering', audioId:'voc0704'},
                { id:5, gender: 'm', punjabi:'ਲਹਿੰਗਾ', starred: false, english:'Indian outfit with a long skirt', audioId:'voc0705'},
                { id:6, gender: 'm', punjabi:'ਕੁੜਤਾ ਪਜਾਮਾ', starred: false, english:'Indian men`s outfit', audioId:'voc0706'},
                { id:7, gender: 'f', punjabi:'ਪਜਾਮੀ', starred: false, english:'leggings', audioId:'voc0707'},
                { id:8, gender: 'f', punjabi:'ਫੁਲਕਾਰੀ', starred: false, english:'Punjabi embroidery style', audioId:'voc0708'},
                { id:9, gender: 'm', punjabi:'ਪਲਾਜ਼ੋ', starred: false, english:'women`s loose pants', audioId:'voc0709'},
                { id:10, gender: 'f', punjabi:'ਸਲਵਾਰ', starred: false, english:'pleated baggy pants', audioId:'voc0710'},
                { id:11, gender: 'f', punjabi:'ਕਮੀਜ਼', starred: false, english:'shirt', audioId:'voc0711'},
                { id:12, gender: 'f', punjabi:'ਜੁੱਤੀ', starred: false, english:'shoe', audioId:'voc0712'},
                { id:13, gender: 'm', punjabi:'ਸੂਟ', starred: false, english:'long shirt with baggy pants', audioId:'voc0713'},
                { id:14, gender: 'f', punjabi:'ਪੱਗ/ਦਸਤਾਰ', starred: false, english:'turban', audioId:'voc0714'},
                { id:15, gender: 'f', punjabi:'ਚੂੜੀ', starred: false, english:'bangle', audioId:'voc0715'},
                { id:16, gender: 'f', punjabi:'ਬਿੰਦੀ', starred: false, english:'dot worn on the forehead', audioId:'voc0716'},
                { id:17, gender: 'm', punjabi:'ਟਿੱਕਾ', starred: false, english:'jewelry worn on the forehead', audioId:'voc0717'},
                { id:18, gender: 'm', punjabi:'ਕਾਂਟੇ', starred: false, english:'dangling earrings', audioId:'voc0718'},
                { id:19, gender: 'f', punjabi:'ਵਾਲੀਆਂ', starred: false, english:'earrings', audioId:'voc0719'},
                { id:20, gender: 'm', punjabi:'ਹਾਰ', starred: false, english:'necklace', audioId:'voc0720'},
                { id:21, gender: 'f', punjabi:'ਅਲਮਾਰੀ', starred: false, english:'closet/cabinet', audioId:'voc0721'},
                { id:22, gender: 'm', punjabi:'ਪਰੈੱਸ', starred: false, english:'iron', audioId:'voc0722'},
                { id:23, gender: 'm', punjabi:'ਮੇਚਾ', starred: false, english:'size', audioId:'voc0723'},
                { id:24, gender: 'm', punjabi:'ਦਾਗ਼', starred: false, english:'stain', audioId:'voc0724'},
                { id:25, gender: 'm', punjabi:'ਰਿਵਾਜ਼', starred: false, english:'trend', audioId:'voc0725'},
                { id:26, gender: 'f', punjabi:'ਮੰਗਣੀ', starred: false, english:'engagement', audioId:'voc0726'},
                { id:27, gender: '', punjabi:'ਮੰਗੇਤਰ', starred: false, english:'fiance', audioId:'voc0727'},
                { id:28, gender: 'm', punjabi:'ਵਿਆਹ', starred: false, english:'wedding', audioId:'voc0728'},
                { id:29, gender: 'f', punjabi:'ਜ਼ਰੂਰਤ', starred: false, english:'need', audioId:'voc0729'},
           
            ],
        Verbs:
            [
                { id:1, gender: '', punjabi:'ਲੱਗਣਾ', starred: false, english:'to appear', audioId:'voc0762'},
                { id:2, gender: '', punjabi:'ਬਦਲਣਾ', starred: false, english:'to change', audioId:'voc0763'},
                { id:3, gender: '', punjabi:'ਤਿਆਰ ਹੋਣਾ', starred: false, english:'to get ready', audioId:'voc0764'},
                { id:4, gender: '', punjabi:'ਜਚਣਾ', starred: false, english:'to look good', audioId:'voc0765'},
                { id:5, gender: '', punjabi:'ਪਾਉਣਾ', starred: false, english:'to wear', audioId:'voc0766'},
                { id:6, gender: '', punjabi:'ਭਰਨਾ', starred: false, english:'to fill', audioId:'voc0767'},
                { id:7, gender: '', punjabi:'ਕੋਲ ਹੋਣਾ', starred: false, english:'to have', audioId:'voc0768'},
            ],
        Others:
        [
            { id:1, gender: '', punjabi:'ਦੁਬਾਰਾ', starred: false, english:'again', audioId:'voc0769'},
            { id:2, gender: '', punjabi:'ਭਾਵੇਂ', starred: false, english:'although', audioId:'voc0770'},
        ],
    },
    "Daily Routines & Hobbies": //mod8
    {
        Adjectives:
            [
                { id:1, gender: '', punjabi:'ਔਖਾ', starred: false, english:'difficult', audioId:'voc0826'},
                { id:2, gender: '', punjabi:'ਸੌਖਾ', starred: false, english:'easy', audioId:'voc0827'},
                { id:3, gender: '', punjabi:'ਵਿਹਲਾ', starred: false, english:'not busy', audioId:'voc0828'},
                { id:4, gender: '', punjabi:'ਘਰੇਲੂ', starred: false, english:'household', audioId:'voc0829'},
                { id:5, gender: '', punjabi:'ਸਖ਼ਤ', starred: false, english:'hard', audioId:'voc0830'},
                { id:6, gender: '', punjabi:'ਮਿਹਨਤੀ', starred: false, english:'hard-working', audioId:'voc0831'},
                { id:7, gender: '', punjabi:'ਦਿਲਚਸਪ', starred: false, english:'interesting', audioId:'voc0832'},
                { id:8, gender: '', punjabi:'ਆਲਸੀ', starred: false, english:'lazy', audioId:'voc0833'},
                { id:9, gender: '', punjabi:'ਜ਼ਿਆਦਾ', starred: false, english:'more', audioId:'voc0834'},
                { id:10, gender: '', punjabi:'ਅਗਲਾ', starred: false, english:'next', audioId:'voc0835'},
                { id:11, gender: '', punjabi:'ਪਿਛਲਾ', starred: false, english:'last', audioId:'voc0836'},
                { id:12, gender: '', punjabi:'ਐਵੇਂ ਈ', starred: false, english:'for no reason', audioId:'voc0837'},
                { id:13, gender: '', punjabi:'ਡੇਢ', starred: false, english:'half past one', audioId:'voc0838'},
                { id:14, gender: '', punjabi:'ਢਾਈ', starred: false, english:'half past two', audioId:'voc0839'},
                { id:15, gender: '', punjabi:'ਸਵਾ', starred: false, english:'quarter past the hour', audioId:'voc0840'},
                { id:16, gender: '', punjabi:'ਪੌਣਾ', starred: false, english:'quarter to', audioId:'voc0841'},
                { id:17, gender: '', punjabi:'ਸਾਢੇ', starred: false, english:'half past', audioId:'voc0842'},
                { id:18, gender: '', punjabi:'ਵਜੇ', starred: false, english:'o`clock', audioId:'voc0843'},
                { id:19, gender: '', punjabi:'ਪੜ੍ਹਾਕੂ', starred: false, english:'studious', audioId:'voc0844'},
            ],
        Nouns:
            [
                { id:1, gender: 'm', punjabi:'ਲੌਢਾ ਵੇਲਾ', starred: false, english:'afternoon', audioId:'voc0801'},
                { id:2, gender: 'm', punjabi:'ਛਾਹ ਵੇਲਾ', starred: false, english:'breakfast', audioId:'voc0802'},
                { id:3, gender: 'f', punjabi:'ਛੁੱਟੀ', starred: false, english:'break', audioId:'voc0803'},
                { id:4, gender: 'm', punjabi:'ਪਰਸੋਂ', starred: false, english:'day before yesterday or day \nafter tomorrow', audioId:'voc0804'},
                { id:5, gender: 'm', punjabi:'ਦਿਨ', starred: false, english:'day', audioId:'voc0805'},
                { id:6, gender: 'm', punjabi:'ਘੰਟਾ', starred: false, english:'hour', audioId:'voc0806'},
                { id:7, gender: 'm', punjabi:'ਮਿੰਟ', starred: false, english:'minute', audioId:'voc0807'},
                { id:8, gender: 'm', punjabi:'ਸਕਿੰਟ', starred: false, english:'second', audioId:'voc0808'},
                { id:9, gender: 'm', punjabi:'ਵੇਲਾ', starred: false, english:'time', audioId:'voc0809'},
                { id:10, gender: 'm', punjabi:'ਅੱਜ', starred: false, english:'today', audioId:'voc0810'},
                { id:11, gender: 'm', punjabi:'ਕੱਲ੍ਹ', starred: false, english:'tomorrow/yesterday', audioId:'voc0811'},
                { id:12, gender: '', punjabi:'ਦਹਾਕਾ', starred: false, english:'decade', audioId:'voc0812'},
                { id:13, gender: '', punjabi:'ਸਦੀ', starred: false, english:'century', audioId:'voc0813'},
                { id:14, gender: 'm', punjabi:'ਕਲੰਡਰ', starred: false, english:'calendar', audioId:'voc0814'},
                { id:15, gender: 'm', punjabi:'ਰੁਝੇਵਾਂ', starred: false, english:'busyness', audioId:'voc0815'},
                { id:16, gender: 'm', punjabi:'ਕੰਘਾ', starred: false, english:'comb', audioId:'voc0816'},
                { id:17, gender: 'f', punjabi:'ਸੇਵਾ', starred: false, english:'service, community service', audioId:'voc0817'},
                { id:18, gender: 'm', punjabi:'ਸ਼ੁਰੂ', starred: false, english:'start', audioId:'voc0818'},
                { id:19, gender: 'f', punjabi:'ਮਿਹਨਤ', starred: false, english:'hard work', audioId:'voc0819'},
                { id:20, gender: 'm', punjabi:'ਸ਼ੌਕ', starred: false, english:'hobby', audioId:'voc0820'},
                { id:21, gender: 'm', punjabi:'ਆਲਸ', starred: false, english:'laziness', audioId:'voc0821'},
                { id:22, gender: 'm', punjabi:'ਇਮਤਿਹਾਨ', starred: false, english:'test', audioId:'voc0822'},
                { id:23, gender: 'm', punjabi:'ਬਿਸਤਰਾ', starred: false, english:'bed', audioId:'voc0823'},
                { id:24, gender: 'm', punjabi:'ਦੋਸਤ', starred: false, english:'male friend', audioId:'voc0824'},
                { id:25, gender: 'f', punjabi:'ਸਹੇਲੀ', starred: false, english:'female friend', audioId:'voc0825'},
            ],
        Verbs:
            [
                { id:1, gender: '', punjabi:'ਲਾਉਣਾ', starred: false, english:'to attend', audioId:'voc0845'},
                { id:2, gender: '', punjabi:'ਸਕਣਾ', starred: false, english:'to be able to do', audioId:'voc0846'},
                { id:3, gender: '', punjabi:'ਉੱਠਣਾ', starred: false, english:'to get up', audioId:'voc0847'},
                { id:4, gender: '', punjabi:'ਚੁੱਕਣਾ', starred: false, english:'to have already done, to lift, \nto pick up', audioId:'voc0848'},
                { id:5, gender: '', punjabi:'ਭੱਜ-ਦੌੜ ਕਰਨੀ', starred: false, english:'to run around', audioId:'voc0849'},
                { id:6, gender: '', punjabi:'ਚੱਲਣਾ', starred: false, english:'to go', audioId:'voc0850'},
                { id:7, gender: '', punjabi:'ਬਿਤਾਉਣਾ', starred: false, english:'to spend time', audioId:'voc0851'},
                { id:8, gender: '', punjabi:'ਨਿਕਲਣਾ', starred: false, english:'to get out/to leave', audioId:'voc0852'},
                { id:9, gender: '', punjabi:'ਘੁੰਮਣਾ-ਫਿਰਨਾ', starred: false, english:'to roam about', audioId:'voc0853'},
            ],
        Others:
        [
            { id:1, gender: '', punjabi:'ਪਹਿਲਾਂ', starred: false, english:'first of all/earlier', audioId:'voc0854'},
            { id:2, gender: '', punjabi:'ਕਈ ਵਾਰੀ', starred: false, english:'sometimes', audioId:'voc0855'},
            { id:3, gender: '', punjabi:'ਛੇਤੀ', starred: false, english:'quickly', audioId:'voc0856'},
            { id:4, gender: '', punjabi:'ਦੇਰ ਤੱਕ', starred: false, english:'till late', audioId:'voc0857'},
            { id:5, gender: '', punjabi:'ਅੱਜ', starred: false, english:'today', audioId:'voc0858'},
            { id:6, gender: '', punjabi:'ਜਿਸ', starred: false, english:'who/at', audioId:'voc0859'},
            { id:7, gender: '', punjabi:'ਬਾਅਦ', starred: false, english:'later', audioId:'voc0860'},
            { id:8, gender: '', punjabi:'ਥੋੜ੍ਹੀ ਦੇਰ ਪਿੱਛੋਂ', starred: false, english:'a little while later', audioId:'voc0861'},
            { id:9, gender: '', punjabi:'ਹੁਣੇ', starred: false, english:'right now', audioId:'voc0862'},
            { id:10, gender: '', punjabi:'ਵਿਚਕਾਰ', starred: false, english:'in the middle/in between', audioId:'voc0863'},
            { id:11, gender: '', punjabi:'ਵੱਜ ਕੇ', starred: false, english:'minutes after the hour', audioId:'voc0864'},
            { id:12, gender: '', punjabi:'ਹੀ', starred: false, english:'only', audioId:'voc0865'},
            { id:13, gender: '', punjabi:'ਹਮੇਸ਼ਾ', starred: false, english:'always', audioId:'voc0866'},
            { id:14, gender: '', punjabi:'ਅਕਸਰ', starred: false, english:'often', audioId:'voc0867'},
        ],
    },
    "College Life, social justice & Seva ": //mod9
    {
        Adjectives:
            [
                { id:1, gender: '', punjabi:'ਜਿੰਨਾ', starred: false, english:'as much', audioId:'voc0901'},
                { id:2, gender: '', punjabi:'ਮਦਦਗਾਰ', starred: false, english:'helpful', audioId:'voc0902'},
                { id:3, gender: '', punjabi:'ਘੱਟ ਗਿਣਤੀ', starred: false, english:'minority', audioId:'voc0903'},
                { id:4, gender: '', punjabi:'ਜੋਸ਼-ਭਰਪੂਰ', starred: false, english:'passionate/exuberant', audioId:'voc0904'},
                { id:5, gender: '', punjabi:'ਮਹੱਤਵਪੂਰਨ', starred: false, english:'significant', audioId:'voc0905'},
                { id:6, gender: '', punjabi:'ਇੰਨਾ', starred: false, english:'so much', audioId:'voc0906'},
                { id:7, gender: '', punjabi:'ਅੱਜ-ਕੱਲ੍ਹ', starred: false, english:'these days', audioId:'voc0907'},
                { id:8, gender: '', punjabi:'ਮੁੱਢਲੀਆਂ', starred: false, english:'undergraduate/elementary', audioId:'voc0908'},
                { id:9, gender: '', punjabi:'ਅਖੀਰਲਾ', starred: false, english:'last', audioId:'voc0909'},
                { id:10, gender: '', punjabi:'ਪਹਿਲਾ', starred: false, english:'first', audioId:'voc0910'},
                { id:11, gender: '', punjabi:'ਬੇਸਮਝ', starred: false, english:'ignorant', audioId:'voc0911'},
                { id:12, gender: '', punjabi:'ਬੇਕਸੂਰ', starred: false, english:'innocent', audioId:'voc0912'},
                { id:13, gender: '', punjabi:'ਜ਼ਰੂਰੀ', starred: false, english:'important', audioId:'voc0913'},
                { id:14, gender: '', punjabi:'ਲਾਜ਼ਮੀ', starred: false, english:'compulsory', audioId:'voc0914'},
                { id:15, gender: '', punjabi:'ਵਿਸ਼ਵ-ਵਿਆਪਕ', starred: false, english:'global', audioId:'voc0915'},
                { id:16, gender: '', punjabi:'ਬਿਹਤਰ', starred: false, english:'better', audioId:'voc0916'},
                { id:17, gender: '', punjabi:'ਚੰਗੇ-ਮੰਦੇ', starred: false, english:'good-bad', audioId:'voc0917'},
                { id:18, gender: '', punjabi:'ਆਰਥਿਕ', starred: false, english:'economic', audioId:'voc0918'},                      
            ],
        Nouns:
            [
                { id:1, gender: 'f', punjabi:'ਅਰਜ਼ੀ', starred: false, english:'application', audioId:'voc0919'},
                { id:2, gender: 'm', punjabi:'ਇੰਤਜ਼ਾਮ', starred: false, english:'arrangement', audioId:'voc0920'},
                { id:3, gender: 'f', punjabi:'ਸੰਸਥਾ', starred: false, english:'association', audioId:'voc0921'},
                { id:4, gender: 'm', punjabi:'ਸੰਤੁਲਨ', starred: false, english:'balance', audioId:'voc0922'},
                { id:5, gender: 'm', punjabi:'ਫ਼ਾਇਦਾ', starred: false, english:'benefit', audioId:'voc0923'},
                { id:6, gender: 'f', punjabi:'ਸਭਾ', starred: false, english:'club', audioId:'voc0924'},
                { id:7, gender: 'f', punjabi:'ਕਮਿਉਨਿਟੀ', starred: false, english:'community', audioId:'voc0925'},
                { id:8, gender: 'm', punjabi:'ਸੰਪਰਕ', starred: false, english:'contact', audioId:'voc0926'},
                { id:9, gender: 'm', punjabi:'ਚੋਣਵਾਂ', starred: false, english:'elective', audioId:'voc0927'},
                { id:10, gender:'m', punjabi:'ਮਹੌਲ', starred: false, english:'environment/atmosphere', audioId:'voc0928'},
                { id:11, gender: 'm', punjabi:'ਤਜਰਬਾ', starred: false, english:'experiment', audioId:'voc0929'},
                { id:12, gender: 'f', punjabi:'ਉਮੀਦ', starred: false, english:'hope', audioId:'voc0930'},
                { id:13, gender: 'f', punjabi:'ਦਿਲਚਸਪੀ', starred: false, english:'interest', audioId:'voc0931'},
                { id:14, gender: 'f', punjabi:'ਰੁਚੀ', starred: false, english:'interest/liking', audioId:'voc0932'},
                { id:15, gender: 'm', punjabi:'ਮੌਕਾ', starred: false, english:'opportunity', audioId:'voc0933'},
                { id:16, gender: 'f', punjabi:'ਸੰਭਾਵਨਾ', starred: false, english:'possibility', audioId:'voc0934'},
                { id:17, gender: 'f', punjabi:'ਨੌਕਰੀ', starred: false, english:'job', audioId:'voc0935'},
                { id:18, gender: 'f', punjabi:'ਖੋਜ', starred: false, english:'research', audioId:'voc0936'},
                { id:19, gender: 'm', punjabi:'ਵਿਸ਼ਾ', starred: false, english:'subject', audioId:'voc0937'},
                { id:20, gender: 'm', punjabi:'ਉਮੀਦਵਾਰ', starred: false, english:'candidate', audioId:'voc0938'},
                { id:21, gender: 'm', punjabi:'ਥੈਲਾ', starred: false, english:'bag', audioId:'voc0939'},
                { id:23, gender: 'm', punjabi:'ਵਿਭਾਗ', starred: false, english:'department', audioId:'voc0940'},
                { id:24, gender: 'm', punjabi:'ਵਿਚਾਰ', starred: false, english:'thought', audioId:'voc0941'},
                { id:25, gender: 'f', punjabi:'ਜਾਣਕਾਰੀ', starred: false, english:'knowledge', audioId:'voc0942'},
                { id:26, gender: 'f', punjabi:'ਦੁਨੀਆ', starred: false, english:'world', audioId:'voc0943'},
                { id:27, gender: 'm', punjabi:'ਵਿਦਿਆਰਥੀ', starred: false, english:'student', audioId:'voc0944'},
                { id:28, gender: 'm', punjabi:'ਵੇਰਵਾ', starred: false, english:'detail', audioId:'voc0945'},
                { id:29, gender: 'f', punjabi:'ਦੋਸਤੀ', starred: false, english:'friendship', audioId:'voc0946'},
                { id:30, gender: 'f', punjabi:'ਜ਼ਿੰਦਗੀ', starred: false, english:'life', audioId:'voc0947'},
                { id:31, gender: 'm', punjabi:'ਇਨਸਾਫ਼ ', starred: false, english:'justice', audioId:'voc0948'},
                { id:32, gender: 'f', punjabi:'ਬੇਇਨਸਾਫੀ', starred: false, english:'injustice', audioId:'voc0949'},
                { id:33, gender: 'f', punjabi:'ਸ਼ਨਾਖਤ/ਪਛਾਣ', starred: false, english:'identity', audioId:'voc0950'},
                { id:34, gender: 'f', punjabi:'ਸਮਾਜ ਸੇਵਾ', starred: false, english:'community service', audioId:'voc0951'},
                { id:35, gender: 'm', punjabi:'ਹਾਲਾਤ', starred: false, english:'situation', audioId:'voc0952'},
                { id:36, gender: 'f', punjabi:'ਹਿੰਸਾ', starred: false, english:'violence', audioId:'voc0953'},
                { id:37, gender: 'm', punjabi:'ਕਾਰਨ', starred: false, english:'reasons', audioId:'voc0954'},
                { id:38, gender: 'm', punjabi:'ਕਿਰਦਾਰ', starred: false, english:'character', audioId:'voc0955'},
                { id:39, gender: 'f', punjabi:'ਘਰੇਲੂ ਹਿੰਸਾ', starred: false, english:'domestic violence', audioId:'voc0956'},
                { id:40, gender: 'f', punjabi:'ਤਾਕਤ', starred: false, english:'power, strength', audioId:'voc0957'},
                { id:41, gender: 'm', punjabi:'ਧੱਕਾ/ਜ਼ਬਰ/ਜ਼ੁਲਮ', starred: false, english:'oppression', audioId:'voc0958'},
                { id:42, gender: 'm', punjabi:'ਪੱਖ', starred: false, english:'aspects', audioId:'voc0959'},
                { id:43, gender: 'm', punjabi:'ਫ਼ਰਜ਼', starred: false, english:'duty', audioId:'voc0960'},
                { id:44, gender: 'm', punjabi:'ਮੁੱਦਾ', starred: false, english:'issue', audioId:'voc0961'},
                { id:45, gender: 'm', punjabi:'ਰੰਗ ਭੇਦ', starred: false, english:'colorism', audioId:'voc0962'},
                { id:46, gender: 'm', punjabi:'ਜਾਤ ਭੇਦ', starred: false, english:'casteism', audioId:'voc0963'},
                { id:47, gender: 'm', punjabi:'ਵਿਤਕਰਾ', starred: false, english:'discrimination', audioId:'voc0964'},
                { id:48, gender: 'm', punjabi:'ਵਿਰੋਧ', starred: false, english:'resistance/opposition', audioId:'voc0965'},
                { id:49, gender: 'f', punjabi:'ਚਮੜੀ', starred: false, english:'skin', audioId:'voc0966'},
            ],
        Verbs:
            [
                { id:1, gender: '', punjabi:'ਦਾਖਲਾ ਲੈਣਾ', starred: false, english:'to be admitted', audioId:'voc0967'},
                { id:2, gender: '', punjabi:'ਪਤਾ ਹੋਣਾ', starred: false, english:'to know', audioId:'voc0968'},
                { id:3, gender: '', punjabi:'ਸਿਖਣਾ', starred: false, english:'to learn', audioId:'voc0969'},
                { id:4, gender: '', punjabi:'ਅੱਗੇ ਵਧਣਾ', starred: false, english:'to move forward', audioId:'voc0970'},
                { id:5, gender: '', punjabi:'ਹਿੱਸਾ ਲੈਣਾ', starred: false, english:'to participate', audioId:'voc0971'},
                { id:6, gender: '', punjabi:'ਸੋਚਣਾ', starred: false, english:'to think', audioId:'voc0972'},
                { id:7, gender: '', punjabi:'ਲੰਘਣਾ', starred: false, english:'to pass', audioId:'voc0973'},
                { id:8, gender: '', punjabi:'ਛੱਡਣਾ', starred: false, english:'to leave', audioId:'voc0974'},
                { id:9, gender: '', punjabi:'ਪੈਣਾ', starred: false, english:'to have to do', audioId:'voc0975'},
                { id:10, gender: '', punjabi:'ਭੇਜਣਾ', starred: false, english:'to send', audioId:'voc0976'},
                { id:11, gender: '', punjabi:'ਚੱਲਣਾ', starred: false, english:'to walk', audioId:'voc0977'},
                { id:12, gender: '', punjabi:'ਸਹਿਣਾ', starred: false, english:'to tolerate', audioId:'voc0978'},
                { id:13, gender: '', punjabi:'ਲੜਨਾ', starred: false, english:'to fight', audioId:'voc0979'},
                { id:14, gender: '', punjabi:'ਅਸਰ ਪੈਣਾ', starred: false, english:'to be impacted', audioId:'voc0980'},
                { id:15, gender: '', punjabi:'ਸਾਹਮਣਾ ਕਰਨਾ', starred: false, english:'to face', audioId:'voc0981'},
                { id:16, gender: '', punjabi:'ਨਜ਼ਰ ਆਉਣਾ', starred: false, english:'to be visible', audioId:'voc0982'},
                { id:17, gender: '', punjabi:'ਜੰਮਣਾ-ਪਲਣਾ', starred: false, english:'being born and growing up', audioId:'voc0983'},
                { id:18, gender: '', punjabi:'ਨਾਲ ਖੜੇ ਹੋਣਾ', starred: false, english:'to stand with', audioId:'voc0984'},
                { id:19, gender: '', punjabi:'ਕਰਵਾਉਣਾ', starred: false, english:'to get done', audioId:'voc0985'},

            ],
        Others:
            [
                { id:1, gender: '', punjabi:'ਜਿਵੇਂ-ਜਿਵੇਂ', starred: false, english:'as /just as', audioId:'voc0986'},
                { id:2, gender: '', punjabi:'ਨਾ ਤਾਂ ਸਿਰਫ਼-ਪਰ', starred: false, english:'not only-but', audioId:'voc0987'},
                { id:3, gender: '', punjabi:'ਸ਼ਾਇਦ', starred: false, english:'perhaps/maybe', audioId:'voc0988'},
                { id:4, gender: '', punjabi:'ਕਿਤੇ', starred: false, english:'somewhere/if/or else', audioId:'voc0989'},
                { id:5, gender: '', punjabi:'ਵਰਗਾ', starred: false, english:'like', audioId:'voc0990'},
                { id:6, gender: '', punjabi:'ਵਿਚਕਾਰ', starred: false, english:'between', audioId:'voc09691'},
                { id:7, gender: '', punjabi:'ਅਨੁਸਾਰ', starred: false, english:'according to', audioId:'voc0992'},
                { id:8, gender: '', punjabi:'ਪਿੱਛੇ', starred: false, english:'behind', audioId:'voc0993'},
                { id:9, gender: '', punjabi:'ਇੱਥੋਂ ਤੱਕ ਕਿ', starred: false, english:'so much so that', audioId:'voc0994'},
                { id:10, gender: '', punjabi:'ਸਰਬੱਤ ਦਾ ਭਲਾ', starred: false, english:'welfare of all', audioId:'voc0995'},
                { id:11, gender: '', punjabi:'ਪਤਾ ਨਹੀਂ', starred: false, english:'no idea', audioId:'voc0996'},
                { id:12, gender: '', punjabi:'ਸਭ ਤੋਂ ਅੱਗੇ', starred: false, english:'at the forefront', audioId:'voc0997'},

            ],
    },
    "Entertainment: Music & Sports": //mod10
    {
        Adjectives:
            [
                { id:1, gender: '', punjabi:'ਇਤਿਹਾਸਕ', starred: false, english:'historical', audioId:'voc1001'},
                { id:2, gender: '', punjabi:'ਧਾਰਮਿਕ', starred: false, english:'religious', audioId:'voc1002'},
                { id:3, gender: '', punjabi:'ਸੱਭਿਆਚਾਰਕ', starred: false, english:'cultural', audioId:'voc1003'},
                { id:4, gender: '', punjabi:'ਸੰਗੀਤਮਈ', starred: false, english:'musical', audioId:'voc1004'},
                { id:5, gender: '', punjabi:'ਵੰਨ-ਸਵੰਨੇ', starred: false, english:'diverse', audioId:'voc1005'},
                { id:6, gender: '', punjabi:'ਪ੍ਰਚੱਲਤ', starred: false, english:'common', audioId:'voc1006'},
                { id:7, gender: '', punjabi:'ਅਜੋਕਾ', starred: false, english:'current', audioId:'voc1007'},
            ],
        Nouns:
            [
                { id:1, gender: 'm', punjabi:'ਸਾਜ਼', starred: false, english:'instrument', audioId:'voc1008'},
                { id:2, gender: 'f', punjabi:'ਰਬਾਬ', starred: false, english:'Rabab', audioId:'voc1009'},
                { id:3, gender: 'm', punjabi:'ਵਾਜਾ', starred: false, english:'harmonium', audioId:'voc1010'},
                { id:4, gender: 'm', punjabi:'ਤਬਲਾ', starred: false, english:'tabla', audioId:'voc1011'},
                { id:5, gender: 'm', punjabi:'ਢੋਲ', starred: false, english:'Indian drum', audioId:'voc1012'},
                { id:6, gender: 'm', punjabi:'ਢੋਲੀ', starred: false, english:'dhol drum player', audioId:'voc1013'},
                { id:7, gender: 'm', punjabi:'ਕਲਾਕਾਰ', starred: false, english:'artist', audioId:'voc1014'},
                { id:8, gender: 'm', punjabi:'ਗਾਇਕ', starred: false, english:'singer', audioId:'voc1015'},
                { id:9, gender: 'm', punjabi:'ਗਾਣਾ', starred: false, english:'song', audioId:'voc1016'},
                { id:10, gender: 'f', punjabi:'ਟੋਲੀ', starred: false, english:'band', audioId:'voc1017'},
                { id:11, gender: 'f', punjabi:'ਕਵੀਸ਼ਰੀ', starred: false, english:'a form of poetry', audioId:'voc1018'},
                { id:12, gender: 'f', punjabi:'ਢਾਡੀ ਵਾਰ', starred: false, english:'a form of poetry/ ballad', audioId:'voc1019'},
                { id:13, gender: 'f', punjabi:'ਬੋਲੀ', starred: false, english:'a form of Punjabi folk songs', audioId:'voc1020'},
                { id:14, gender: 'f', punjabi:'ਤਾੜੀ', starred: false, english:'clap', audioId:'voc1021'},
                { id:15, gender: 'm', punjabi:'ਨਾਚ', starred: false, english:'dance', audioId:'voc1022'},
                { id:16, gender: 'm', punjabi:'ਭੰਗੜਾ', starred: false, english:'a form of Punjabi dance', audioId:'voc1023'},
                { id:17, gender: 'm', punjabi:'ਗਿੱਧਾ', starred: false, english:'a form of women`s dance', audioId:'voc1024'},
                { id:18, gender: 'm', punjabi:'ਮਲਵਈ ਗਿੱਧਾ', starred: false, english:'men`s dance from Malwa', audioId:'voc1025'},
                { id:19, gender: 'm', punjabi:'ਝੂਮਰ', starred: false, english:'a form of dance', audioId:'voc1026'},
                { id:20, gender: 'm', punjabi:'ਨਖ਼ਰਾ', starred: false, english:'attitude', audioId:'voc1027'},
                { id:21, gender: 'm', punjabi:'ਜਥਾ', starred: false, english:'group/troop', audioId:'voc1028'},
                { id:22, gender: 'm', punjabi:'ਮਨੋਰੰਜਨ', starred: false, english:'entertainment', audioId:'voc1029'},
                { id:23, gender: 'm', punjabi:'ਪ੍ਰਦਰਸ਼ਨ', starred: false, english:'performance', audioId:'voc1030'},
                { id:24, gender: 'f', punjabi:'ਖੇਡ', starred: false, english:'sports', audioId:'voc1031'},
                { id:25, gender: 'm', punjabi:'ਗਤਕਾ', starred: false, english:'a form of martial arts', audioId:'voc1032'},
                { id:26, gender: 'm', punjabi:'ਸ਼ਸਤਰ', starred: false, english:'weapons', audioId:'voc1033'},
                { id:27, gender: 'f', punjabi:'ਕਬੱਡੀ', starred: false, english:'a traditional sport of Punjab', audioId:'voc1034'},
                { id:28, gender: 'f', punjabi:'ਕ੍ਰਿਕਟ', starred: false, english:'cricket', audioId:'voc1035'},
                { id:29, gender: 'f', punjabi:'ਹਾਕੀ', starred: false, english:'hockey', audioId:'voc1036'},
                { id:30, gender: 'm', punjabi:'ਖਿਡਾਰੀ', starred: false, english:'player', audioId:'voc1037'},
                { id:31, gender: 'm', punjabi:'ਬੱਲਾ', starred: false, english:'bat', audioId:'voc1038'},
                { id:32, gender: 'm', punjabi:'ਗੇਂਦ', starred: false, english:'ball', audioId:'voc1039'},
                { id:33, gender: 'm', punjabi:'ਦਰਸ਼ਕ', starred: false, english:'viewers', audioId:'voc1040'},
                { id:34, gender: 'f', punjabi:'ਸੱਟ', starred: false, english:'injury', audioId:'voc1041'},
                { id:35, gender: 'm', punjabi:'ਇਨਾਮ', starred: false, english:'award/prize', audioId:'voc1042'},
                { id:36, gender: 'f', punjabi:'ਯਾਦ', starred: false, english:'memory', audioId:'voc1043'},
                { id:37, gender: 'm', punjabi:'ਰੌਲਾ', starred: false, english:'loud noise', audioId:'voc1044'},
                { id:38, gender: 'f', punjabi:'ਖੱਪ', starred: false, english:'noise', audioId:'voc1045'},
                { id:39, gender: 'f', punjabi:'ਧਮਾਲ', starred: false, english:'noise/uproar/frolic', audioId:'voc1046'},
                { id:40, gender: 'f', punjabi:'ਪੀਂਘ', starred: false, english:'swing', audioId:'voc1047'},
                { id:41, gender: 'f', punjabi:'ਮਹੱਤਤਾ', starred: false, english:'significance', audioId:'voc1048'},
                { id:42, gender: 'm', punjabi:'ਭਾਗ', starred: false, english:'part', audioId:'voc1049'},
            ],
        Verbs:
            [
                { id:1, gender: '', punjabi:'ਮੰਨਣਾ', starred: false, english:'to agree/to accept', audioId:'voc1050'},
                { id:2, gender: '', punjabi:'ਨੱਚਣਾ', starred: false, english:'to dance', audioId:'voc1051'},
                { id:3, gender: '', punjabi:'ਦੌੜਨਾ', starred: false, english:'to run', audioId:'voc1052'},
                { id:4, gender: '', punjabi:'ਗਾਉਣਾ', starred: false, english:'to sing', audioId:'voc1053'},
                { id:5, gender: '', punjabi:'ਹਾਰਨਾ', starred: false, english:'to lose', audioId:'voc1054'},
                { id:6, gender: '', punjabi:'ਜਿੱਤਣਾ', starred: false, english:'to win', audioId:'voc1055'},
                { id:7, gender: '', punjabi:'ਝੂਟਣਾ', starred: false, english:'to swing', audioId:'voc1056'},
                { id:8, gender: '', punjabi:'ਮਾਰਨਾ', starred: false, english:'to beat', audioId:'voc1057'},
                { id:9, gender: '', punjabi:'ਵਜਾਉਣਾ', starred: false, english:'to play (a musical instrument)', audioId:'voc1058'},
                { id:10, gender: '', punjabi:'ਦਿਖਾਉਣਾ', starred: false, english:'to show', audioId:'voc1059'},
                { id:11, gender: '', punjabi:'ਅਭਿਆਸ ਕਰਨਾ', starred: false, english:'to practice', audioId:'voc1060'},
            ],
        Others:
        [
            { id:1, gender: '', punjabi:'ਹਾਲੀ ਵੀ/ਅਜੇ ਵੀ', starred: false, english:'still', audioId:'voc1061'},
            { id:2, gender: '', punjabi:'ਇਹੋ ਹੀ', starred: false, english:'this only', audioId:'voc1062'},
            { id:3, gender: '', punjabi:'ਬਾਕੀ ਦੀ', starred: false, english:'rest of', audioId:'voc1063'},
            { id:4, gender: '', punjabi:'ਸਗੋਂ', starred: false, english:'not only…but', audioId:'voc1064'},
        ],
    },
    "Traveling to Punjab: The Land of 5 Rivers": //mod11
    {
        Adjectives:
            [
                { id:1, gender: '', punjabi:'ਸੁਹਾਵਣਾ', starred: false, english:'pleasant', audioId:'voc1101'},
                { id:2, gender: '', punjabi:'ਵੱਖਰਾ', starred: false, english:'separate/different/unique', audioId:'voc1102'},
                { id:3, gender: '', punjabi:'ਦੇਖਣ ਯੋਗ', starred: false, english:'worth seeing', audioId:'voc1103'},
            ],
        Nouns:
            [
                { id:1, gender: 'm', punjabi:'ਪੂਰਬ', starred: false, english:'East', audioId:'voc1104'},
                { id:2, gender: 'm', punjabi:'ਪੱਛਮ', starred: false, english:'West', audioId:'voc1105'},
                { id:3, gender: 'm', punjabi:'ਉੱਤਰ', starred: false, english:'North', audioId:'voc1106'},
                { id:4, gender: 'm', punjabi:'ਦੱਖਣ', starred: false, english:'South', audioId:'voc1107'},
                { id:5, gender: 'm', punjabi:'ਪਿੰਡ', starred: false, english:'village', audioId:'voc1108'},
                { id:6, gender: 'm', punjabi:'ਖੇਤ', starred: false, english:'field', audioId:'voc1109'},
                { id:7, gender: 'm', punjabi:'ਸ਼ਹਿਰ', starred: false, english:'city', audioId:'voc1110'},
                { id:8, gender: 'f', punjabi:'ਇਮਾਰਤ', starred: false, english:'building', audioId:'voc1111'},
                { id:9, gender: 'm', punjabi:'ਢਾਬਾ', starred: false, english:'typical Punjabi restaurant', audioId:'voc1112'},
                { id:10, gender: 'm', punjabi:'ਸਫ਼ਰ', starred: false, english:'travel', audioId:'voc1113'},
                { id:11, gender: 'm', punjabi:'ਹਵਾਈ ਜਹਾਜ', starred: false, english:'airplane', audioId:'voc1114'},
                { id:12, gender: 'm', punjabi:'ਹਵਾਈ ਅੱਡਾ', starred: false, english:'airport', audioId:'voc1115'},
                { id:13, gender: 'f', punjabi:'ਬੱਸ', starred: false, english:'bus', audioId:'voc1116'},
                { id:14, gender: 'm', punjabi:'ਅੱਡਾ', starred: false, english:'stand', audioId:'voc1117'},
                { id:15, gender: 'f', punjabi:'ਗੱਡੀ', starred: false, english:'car', audioId:'voc1118'},
                { id:16, gender: 'm', punjabi:'ਟੈਂਪੂ', starred: false, english:'auto rickshaw', audioId:'voc1119'},
                { id:17, gender: 'm', punjabi:'ਰਿਕਸ਼ਾ', starred: false, english:'rickshaw', audioId:'voc1120'},
                { id:18, gender: 'f', punjabi:'ਰੇਲ ਗੱਡੀ', starred: false, english:'train', audioId:'voc1121'},
                { id:19, gender: 'm', punjabi:'ਕਿਰਾਇਆ', starred: false, english:'fare', audioId:'voc1122'},
                { id:20, gender: 'f', punjabi:'ਆਵਾਜਾਈ', starred: false, english:'transportation', audioId:'voc1123'},
                { id:21, gender: 'm', punjabi:'ਦੌਰਾ', starred: false, english:'trip', audioId:'voc1124'},
                { id:22, gender: 'f', punjabi:'ਛੁੱਟੀ', starred: false, english:'vacation', audioId:'voc1125'},
                { id:23, gender: 'm', punjabi:'ਹਰਿਮੰਦਰ ਸਾਹਿਬ', starred: false, english:'Golden Temple', audioId:'voc1126'},
                { id:24, gender: 'm', punjabi:'ਮੌਸਮ', starred: false, english:'weather', audioId:'voc1127'},
                { id:25, gender: 'm', punjabi:'ਦਰਿਆ', starred: false, english:'river', audioId:'voc1128'},
                { id:26, gender: 'f', punjabi:'ਨਹਿਰ', starred: false, english:'canal', audioId:'voc1129'},
                { id:27, gender: 'm', punjabi:'ਹੁੱਸੜ', starred: false, english:'humidity', audioId:'voc1130'},
                { id:28, gender: 'm', punjabi:'ਮੀਂਹ', starred: false, english:'rain', audioId:'voc1131'},
                { id:29, gender: 'f', punjabi:'ਹਨੇਰੀ', starred: false, english:'storm', audioId:'voc1132'},
                { id:30, gender: 'f', punjabi:'ਧੁੱਪ', starred: false, english:'sunshine', audioId:'voc1133'},
                { id:31, gender: 'm', punjabi:'ਬੱਦਲ', starred: false, english:'cloud', audioId:'voc1134'},
                { id:32, gender: 'f', punjabi:'ਵਾਰੀ', starred: false, english:'turn', audioId:'voc1135'},
                { id:33, gender: 'm', punjabi:'ਅਨੰਦ', starred: false, english:'bliss', audioId:'voc1136'},
                { id:34, gender: 'f', punjabi:'ਪਰੇਸ਼ਾਨੀ', starred: false, english:'discomfort', audioId:'voc1137'},
                { id:35, gender: 'm', punjabi:'ਪ੍ਰਸ਼ਨ/ਸਵਾਲ', starred: false, english:'question', audioId:'voc1138'},
                { id:36, gender: 'm', punjabi:'ਉੱਤਰ/ਜਵਾਬ', starred: false, english:'answer', audioId:'voc1139'},
                { id:37, gender: 'm', punjabi:'ਕਨੂੰਨ', starred: false, english:'law', audioId:'voc1140'},
                { id:38, gender: 'm', punjabi:'ਨਿਯਮ', starred: false, english:'rule', audioId:'voc1141'},
            ],
        Verbs:
            [
                { id:1, gender: '', punjabi:'ਵਾਪਸ ਆਉਣਾ', starred: false, english:'to come back', audioId:'voc1142'},
                { id:2, gender: '', punjabi:'ਰੁਕਣਾ', starred: false, english:'to stop over', audioId:'voc1143'},
                { id:3, gender: '', punjabi:'ਠਹਿਰਨਾ', starred: false, english:'to stay', audioId:'voc1144'},
                { id:4, gender: '', punjabi:'ਫ਼ੋਟੋ ਖਿੱਚਣੀ', starred: false, english:'to take a picture', audioId:'voc1145'},
                { id:5, gender: '', punjabi:'ਪਹੁੰਚਣਾ', starred: false, english:'to reach', audioId:'voc1146'},
            ],
        Others:
        [
            { id:1, gender: '', punjabi:'ਹੁਣੇ ਹੀ', starred: false, english:'just recently', audioId:'voc1147'},
            { id:2, gender: '', punjabi:'ਪਿਛਲੀ ਵਾਰੀ', starred: false, english:'last time', audioId:'voc1148'},
            { id:3, gender: '', punjabi:'ਪਿੱਛੇ ਜਿਹੇ', starred: false, english:'a short while ago', audioId:'voc1149'},
            { id:4, gender: '', punjabi:'ਕਦੀ ਨਹੀਂ', starred: false, english:'never', audioId:'voc1150'},
            { id:5, gender: '', punjabi:'ਤਕਰੀਬਨ', starred: false, english:'almost', audioId:'voc1151'},
            { id:6, gender: '', punjabi:'ਰਾਹ ਵਿਚ', starred: false, english:'on the way', audioId:'voc1152'},
        ],
    },
    "Exploring the City": //mod12
    {
        Adjectives:
            [
                { id:1, gender: '', punjabi:'ਦੂਰ', starred: false, english:'far away', audioId:'voc1201'},
                { id:2, gender: '', punjabi:'ਨੇੜੇ', starred: false, english:'nearby', audioId:'voc1202'},
                { id:3, gender: '', punjabi:'ਸ਼ਾਕਾਹਾਰੀ', starred: false, english:'vegetarian', audioId:'voc1203'},
                { id:4, gender: '', punjabi:'ਮਾਸਾਹਾਰੀ', starred: false, english:'non-vegetarian', audioId:'voc1204'},
                { id:5, gender: '', punjabi:'ਖੱਬਾ', starred: false, english:'left side', audioId:'voc1205'},
                { id:6, gender: '', punjabi:'ਸੱਜਾ', starred: false, english:'right side', audioId:'voc1206'},
                { id:7, gender: '', punjabi:'ਸਿੱਧਾ', starred: false, english:'straight', audioId:'voc1207'},
                { id:8, gender: '', punjabi:'ਅਮੀਰ', starred: false, english:'elite', audioId:'voc1208'},
                { id:9, gender: '', punjabi:'ਜ਼ਾਹਰ', starred: false, english:'visible/obvious', audioId:'voc1209'},
                { id:10, gender: '', punjabi:'ਅੰਦਰਲਾ', starred: false, english:'inner', audioId:'voc1210'},
            ],
        Nouns:
            [
                { id:1, gender: 'f', punjabi:'ਉਮਰ', starred: false, english:'life/age', audioId:'voc1211'},
                { id:2, gender: 'm', punjabi:'ਪੈਸਾ', starred: false, english:'money', audioId:'voc1212'},
                { id:3, gender: 'm', punjabi:'ਫ਼ਰਕ', starred: false, english:'difference', audioId:'voc1213'},
                { id:4, gender: 'm', punjabi:'ਜਸ਼ਨ', starred: false, english:'celebration', audioId:'voc1214'},
                { id:5, gender: 'm', punjabi:'ਫੱਟਾ', starred: false, english:'board', audioId:'voc1215'},
                { id:6, gender: 'm', punjabi:'ਪਹਾੜ', starred: false, english:'mountains', audioId:'voc1216'},
                { id:7, gender: 'm', punjabi:'ਬਾਗ', starred: false, english:'garden', audioId:'voc1217'},
                { id:8, gender: 'f', punjabi:'ਗਲੀ', starred: false, english:'street', audioId:'voc1218'},
                { id:9, gender: 'f', punjabi:'ਠੰਢਕ', starred: false, english:'coolness', audioId:'voc1219'},
                { id:10, gender: 'm', punjabi:'ਅਜਾਇਬ ਘਰ', starred: false, english:'museum', audioId:'voc1220'},
                { id:11, gender: 'm', punjabi:'ਮੁਹੱਲਾ', starred: false, english:'ward/urban district', audioId:'voc1221'},
                { id:12, gender: 'f', punjabi:'ਰੁੱਤ', starred: false, english:'season', audioId:'voc1222'},
                { id:13, gender: 'm', punjabi:'ਪੁਲ', starred: false, english:'bridge', audioId:'voc1223'},
                { id:14, gender: 'm', punjabi:'ਦਰਵਾਜਾ', starred: false, english:'gate', audioId:'voc1224'},
                { id:15, gender: 'f', punjabi:'ਹਵੇਲੀ', starred: false, english:'mansion', audioId:'voc1225'},
                { id:16, gender: 'm', punjabi:'ਹਾਦਸਾ', starred: false, english:'accident', audioId:'voc1226'},
                { id:17, gender: 'f', punjabi:'ਸਮਾਧੀ', starred: false, english:'tomb', audioId:'voc1227'},
                { id:18, gender: 'm', punjabi:'ਇਲਾਕਾ', starred: false, english:'area/locality', audioId:'voc1228'},
                { id:19, gender: 'm', punjabi:'ਫੁੱਲ-ਬੂਟੇ', starred: false, english:'flower and plant', audioId:'voc1229'},
                { id:20, gender: 'm', punjabi:'ਸ਼ਹੀਦ', starred: false, english:'martyr', audioId:'voc1230'},
                { id:21, gender: 'm', punjabi:'ਮਹਿਮਾਨ-ਨਿਵਾਜ਼ੀ', starred: false, english:'hospitality', audioId:'voc1231'},
                { id:22, gender: 'm', punjabi:'ਤਰੀਕਾ', starred: false, english:'way', audioId:'voc1232'},
                { id:23, gender: 'm', punjabi:'ਇਨਸਾਨ', starred: false, english:'person', audioId:'voc1233'},
                { id:24, gender: 'f', punjabi:'ਖੁਸ਼ਕਿਸਮਤੀ', starred: false, english:'good fortune', audioId:'voc1234'},
                { id:25, gender: 'm', punjabi:'ਗੱਡਾ', starred: false, english:'ox cart', audioId:'voc1235'},
                { id:26, gender: 'm', punjabi:'ਫ਼ੌਜੀ', starred: false, english:'soldier', audioId:'voc1236'},
                { id:27, gender: 'm', punjabi:'ਸਮਾਨ', starred: false, english:'luggage', audioId:'voc1237'},
                { id:28, gender: 'm', punjabi:'ਇੱਟ-ਪੱਥਰ', starred: false, english:'brick-stone', audioId:'voc1238'},
                { id:29, gender: 'm', punjabi:'ਚੌਂਕ', starred: false, english:'crossroads', audioId:'voc1239'},
                { id:30, gender: 'm', punjabi:'ਫੁਹਾਰਾ', starred: false, english:'fountain', audioId:'voc1240'},
                { id:31, gender: 'f', punjabi:'ਰੇਹੜੀ', starred: false, english:'cart', audioId:'voc1241'},
                { id:32, gender: 'm', punjabi:'ਸੰਗਮਰਮਰ', starred: false, english:'marble', audioId:'voc1242'},
            ],
        Verbs:
            [
                { id:1, gender: '', punjabi:'ਬਿਤਾਉਣਾ', starred: false, english:'to spend', audioId:'voc1243'},
                { id:2, gender: '', punjabi:'ਡਰਨਾ', starred: false, english:'to be scared', audioId:'voc1244'},
                { id:3, gender: '', punjabi:'ਦੱਸਣਾ', starred: false, english:'to tell', audioId:'voc1245'},
                { id:4, gender: '', punjabi:'ਲੱਭਣਾ', starred: false, english:'to find', audioId:'voc1246'},
                { id:5, gender: '', punjabi:'ਮੁੜਨਾ', starred: false, english:'to turn', audioId:'voc1247'},
                { id:6, gender: '', punjabi:'ਚੜ੍ਹਨਾ', starred: false, english:'to climb/to ride', audioId:'voc1248'},
                { id:7, gender: '', punjabi:'ਪੈਦਲ ਜਾਣਾ', starred: false, english:'to walk', audioId:'voc1249'},
                { id:8, gender: '', punjabi:'ਤੁਰਨਾ-ਫਿਰਨਾ', starred: false, english:'to explore', audioId:'voc1250'},
                { id:9, gender: '', punjabi:'ਗੁਆਚ ਜਾਣਾ', starred: false, english:'to get lost', audioId:'voc1251'},
                { id:10, gender: '', punjabi:'ਸਵਾਰੀ ਕਰਨਾ', starred: false, english:'to ride', audioId:'voc1252'},
                { id:11, gender: '', punjabi:'ਰਾਹ ਪੁੱਛਣਾ', starred: false, english:'to ask for directions', audioId:'voc1253'},
                { id:12, gender: '', punjabi:'ਬੁਲਾਉਣਾ', starred: false, english:'to say', audioId:'voc1254'},
                { id:13, gender: '', punjabi:'ਬਣਵਾਉਣਾ', starred: false, english:'to get made', audioId:'voc1255'},
            ],
        Others:
        [
            { id:1, gender: '', punjabi:'ਅਕਸਰ', starred: false, english:'often', audioId:'voc1256'},
            { id:2, gender: '', punjabi:'ਮੁਤਾਬਕ', starred: false, english:'according to', audioId:'voc1257'},
        ],
    },
}